### ISSUE TITLE
fontconfig compilation fails

### ISSUE THREAD

**Issue by pietrovismara** [amethyst/amethyst#1202]
On Mint 18.3, trying to compile the basic amethyst project created with `amethyst new <project-name>` always fails for me.

```
$ RUST_BACKTRACE=verbose cargo build
   Compiling servo-fontconfig-sys v4.0.7
   Compiling genmesh v0.6.2
   Compiling rodio v0.8.1
   Compiling x11-clipboard v0.3.0
   Compiling gfx v0.17.1
   Compiling glsl-layout v0.1.1
   Compiling shrev v1.0.1
   Compiling crossbeam-channel v0.2.6
   Compiling gfx_gl v0.5.0
   Compiling glutin v0.18.0
   Compiling winit v0.17.2
   Compiling specs v0.12.3
   Compiling clipboard v0.5.0
   Compiling crossbeam v0.4.1
   Compiling specs-hierarchy v0.2.1
   Compiling amethyst_core v0.4.0
   Compiling gfx_glyph v0.13.0
   Compiling amethyst_assets v0.5.0
   Compiling amethyst_input v0.5.0
   Compiling amethyst_derive v0.2.0
   Compiling amethyst_network v0.2.0
   Compiling gfx_device_gl v0.15.3
   Compiling gfx_window_glutin v0.26.0
error: failed to run custom build command for `servo-fontconfig-sys v4.0.7`
process didn't exit successfully: `/home/pietro/Documents/projects/gamez/totalone-rust/target/debug/build/servo-fontconfig-sys-1a591f26f3e7a72d/build-script-build` (exit code: 101)
--- stdout
cd /home/pietro/Documents/projects/gamez/totalone-rust/target/debug/build/servo-fontconfig-sys-8f4e1bbb9376e41c/out && \
	CC="gcc" \
	AR="ar" \
	FREETYPE_CFLAGS="" \
	FREETYPE_LIBS="" \
	CFLAGS=""" -fPIC" \
	/home/pietro/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-fontconfig-sys-4.0.7/configure \
	--disable-docs \
	--disable-shared \
	 \
	--host=x86_64-unknown-linux-gnu --sysconfdir=/etc --localstatedir=/var
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for x86_64-unknown-linux-gnu-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for x86_64-unknown-linux-gnu-gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for x86_64-unknown-linux-gnu-pkg-config... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for RM macro... rm -f
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for x86_64-unknown-linux-gnu-objdump... no
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for x86_64-unknown-linux-gnu-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for x86_64-unknown-linux-gnu-ar... ar
checking for archiver @FILE support... @
checking for x86_64-unknown-linux-gnu-strip... strip
checking for x86_64-unknown-linux-gnu-ranlib... no
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for x86_64-unknown-linux-gnu-mt... no
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... cflags:  -fPIC
cppflags: 
ldflags:  -Wl,-rpath -Wl,/foo
libs: 
GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking for dirent.h that defines DIR... yes
checking for library containing opendir... cflags:  -fPIC
cppflags: 
ldflags: 
libs: 
none required
checking for ANSI C header files... (cached) yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking regex.h usability... yes
checking regex.h presence... yes
checking for regex.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking sys/statvfs.h usability... yes
checking sys/statvfs.h presence... yes
checking for sys/statvfs.h... yes
checking sys/vfs.h usability... yes
checking sys/vfs.h presence... yes
checking for sys/vfs.h... yes
checking sys/statfs.h usability... yes
checking sys/statfs.h presence... yes
checking for sys/statfs.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/mount.h usability... yes
checking sys/mount.h presence... yes
checking for sys/mount.h... yes
checking for stdint types... stdint.h (shortcircuit)
make use of stdint.h in src/fcstdint.h (assuming C99 compatible system)
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for flexible array members... yes
checking for pid_t... yes
checking for vprintf... cflags:  -fPIC
cppflags: 
ldflags: 
libs: 
conftest.c:65:6: warning: conflicting types for built-in function 'vprintf'
 char vprintf ();
      ^
yes
checking for _doprnt... cflags:  -fPIC
cppflags: 
ldflags: 
libs: 
/tmp/cc6J7esM.o: In function `main':
conftest.c:(.text+0xa): undefined reference to `_doprnt'
collect2: error: ld returned 1 exit status
no
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... (cached) yes
checking for getpagesize... cflags:  -fPIC
cppflags: 
ldflags: 
libs: 
yes
checking for working mmap... yes
checking for link... cflags:  -fPIC
cppflags: 
ldflags: 
libs: 
yes
checking for mkstemp... cflags:  -fPIC
cppflags: 
ldflags: 
libs: 
yes
checking for mkostemp... cflags:  -fPIC
cppflags: 
ldflags: 
libs: 
yes
checking for _mktemp_s... cflags:  -fPIC
cppflags: 
ldflags: 
libs: 
/tmp/ccIBmC1L.o: In function `main':
conftest.c:(.text+0xa): undefined reference to `_mktemp_s'
collect2: error: ld returned 1 exit status
no
checking for mkdtemp... cflags:  -fPIC
cppflags: 
ldflags: 
libs: 
yes
checking for getopt... cflags:  -fPIC
cppflags: 
ldflags: 
libs: 
yes
checking for getopt_long... cflags:  -fPIC
cppflags: 
ldflags: 
libs: 
yes
checking for getprogname... cflags:  -fPIC
cppflags: 
ldflags: 
libs: 
/tmp/ccVTVd72.o: In function `main':
conftest.c:(.text+0xa): undefined reference to `getprogname'
collect2: error: ld returned 1 exit status
no
checking for getexecname... cflags:  -fPIC
cppflags: 
ldflags: 
libs: 
/tmp/cczwfHil.o: In function `main':
conftest.c:(.text+0xa): undefined reference to `getexecname'
collect2: error: ld returned 1 exit status
no
checking for rand... cflags:  -fPIC
cppflags: 
ldflags: 
libs: 
yes
checking for random... cflags:  -fPIC
cppflags: 
ldflags: 
libs: 
yes
checking for lrand48... cflags:  -fPIC
cppflags: 
ldflags: 
libs: 
yes
checking for random_r... cflags:  -fPIC
cppflags: 
ldflags: 
libs: 
yes
checking for rand_r... cflags:  -fPIC
cppflags: 
ldflags: 
libs: 
yes
checking for readlink... cflags:  -fPIC
cppflags: 
ldflags: 
libs: 
yes
checking for regcomp... cflags:  -fPIC
cppflags: 
ldflags: 
libs: 
yes
checking for regerror... cflags:  -fPIC
cppflags: 
ldflags: 
libs: 
yes
checking for regexec... cflags:  -fPIC
cppflags: 
ldflags: 
libs: 
yes
checking for regfree... cflags:  -fPIC
cppflags: 
ldflags: 
libs: 
yes
checking for fstatvfs... cflags:  -fPIC
cppflags: 
ldflags: 
libs: 
yes
checking for fstatfs... cflags:  -fPIC
cppflags: 
ldflags: 
libs: 
yes
checking for lstat... cflags:  -fPIC
cppflags: 
ldflags: 
libs: 
yes
checking for posix_fadvise in fcntl.h... fcntl.h
checking for scandir... yes
checking for struct statvfs.f_basetype... no
checking for struct statvfs.f_fstypename... no
checking for struct statfs.f_flags... yes
checking for struct statfs.f_fstypename... no
checking for struct dirent.d_type... yes
checking for FREETYPE... yes
checking for FT_Get_Next_Char... cflags:  -fPIC -I/usr/include/freetype2
cppflags: 
ldflags: 
libs:  -lfreetype
yes
checking for FT_Get_BDF_Property... cflags:  -fPIC -I/usr/include/freetype2
cppflags: 
ldflags: 
libs:  -lfreetype
yes
checking for FT_Get_PS_Font_Info... cflags:  -fPIC -I/usr/include/freetype2
cppflags: 
ldflags: 
libs:  -lfreetype
yes
checking for FT_Has_PS_Glyph_Names... cflags:  -fPIC -I/usr/include/freetype2
cppflags: 
ldflags: 
libs:  -lfreetype
yes
checking for FT_Get_X11_Font_Format... cflags:  -fPIC -I/usr/include/freetype2
cppflags: 
ldflags: 
libs:  -lfreetype
yes
checking for FT_Select_Size... cflags:  -fPIC -I/usr/include/freetype2
cppflags: 
ldflags: 
libs:  -lfreetype
yes
checking for FT_Bitmap_Size.y_ppem... yes
checking for EXPAT... no
checking expat.h usability... no
checking expat.h presence... no
checking for expat.h... no
checking xmlparse.h usability... no
checking xmlparse.h presence... no
checking for xmlparse.h... no
makefile.cargo:83: recipe for target '/home/pietro/Documents/projects/gamez/totalone-rust/target/debug/build/servo-fontconfig-sys-8f4e1bbb9376e41c/out/Makefile' failed

--- stderr
configure: error: 
*** expat is required. or try to use --enable-libxml2
make: *** [/home/pietro/Documents/projects/gamez/totalone-rust/target/debug/build/servo-fontconfig-sys-8f4e1bbb9376e41c/out/Makefile] Error 1
thread 'main' panicked at 'assertion failed: Command::new("make").env("MAKEFLAGS",
                         env::var("CARGO_MAKEFLAGS").unwrap_or_default()).args(&["-R",
                                                                                 "-f",
                                                                                 "makefile.cargo"]).status().unwrap().success()', /home/pietro/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-fontconfig-sys-4.0.7/build.rs:20:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::begin_panic
             at /rustc/8b096314a6381e28834ddb1e662ce90e5b32736b/src/libstd/panicking.rs:410
   6: build_script_build::main
             at ./build.rs:20
   7: std::rt::lang_start::{{closure}}
             at /rustc/8b096314a6381e28834ddb1e662ce90e5b32736b/src/libstd/rt.rs:74
   8: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
   9: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  10: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  11: std::rt::lang_start
             at /rustc/8b096314a6381e28834ddb1e662ce90e5b32736b/src/libstd/rt.rs:74
  12: main
  13: __libc_start_main
  14: _start

warning: build failed, waiting for other jobs to finish...
error: build failed

```

Unfortunately I don't know how to solve this issue or how to pass the `--enable-libxml2` flag to servo-fontconfig-sys. Any suggestion?

**Comment by pietrovismara** [comment]
Installing `libfontconfig1-dev` with `apt install libfontconfig1-dev` solved this issue.
