### ISSUE TITLE
[BUG] Removing the Parent causes a panic

### ISSUE THREAD

**Issue by Awpteamoose** [amethyst/amethyst#1550]
## Description

Removing the Parent component from an entity causes a panic.

## Reproduction Steps

1. Create an entity
2. Create another entity
3. Assign the first entity as a Parent
4. Remove the Parent with WriteStorage

## What You Expected to Happen

The Parent component is removed.

## What Actually Happened

Thread panic:
```
thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'Unreachable: All entities in `ParentHierarchy` should also be in `Parent`Unreachable: All entities in `ParentHierarchy` should also be in `Parents`', src\libcore\option.rs', :src\libcore\option.rs1036::10365:
5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/3c3d3c1777041200bb7ed7a65b6562d62899778c\/src\libstd\sys\windows\backtrace\mod.rs:95
   1: std::sys::windows::backtrace::unwind_backtrace
             at /rustc/3c3d3c1777041200bb7ed7a65b6562d62899778c\/src\libstd\sys\windows\backtrace\mod.rs:82
   2: std::sys_common::backtrace::_print
             at /rustc/3c3d3c1777041200bb7ed7a65b6562d62899778c\/src\libstd\sys_common\backtrace.rs:71
   3: std::sys_common::backtrace::print
             at /rustc/3c3d3c1777041200bb7ed7a65b6562d62899778c\/src\libstd\sys_common\backtrace.rs:59
   4: std::panicking::default_hook::{{closure}}
             at /rustc/3c3d3c1777041200bb7ed7a65b6562d62899778c\/src\libstd\panicking.rs:197
   5: std::panicking::default_hook
             at /rustc/3c3d3c1777041200bb7ed7a65b6562d62899778c\/src\libstd\panicking.rs:211
   6: std::panicking::rust_panic_with_hook
             at /rustc/3c3d3c1777041200bb7ed7a65b6562d62899778c\/src\libstd\panicking.rs:474
   7: std::panicking::continue_panic_fmt
             at /rustc/3c3d3c1777041200bb7ed7a65b6562d62899778c\/src\libstd\panicking.rs:381
   8: std::panicking::rust_begin_panic
             at /rustc/3c3d3c1777041200bb7ed7a65b6562d62899778c\/src\libstd\panicking.rs:308
   9: core::panicking::panic_fmt
             at /rustc/3c3d3c1777041200bb7ed7a65b6562d62899778c\/src\libcore\panicking.rs:85
  10: core::option::expect_failed
             at /rustc/3c3d3c1777041200bb7ed7a65b6562d62899778c\/src\libcore\option.rs:1036
  11: core::option::Option<amethyst_core::transform::components::parent::Parent*>::expect<amethyst_core::transform::components::parent::Parent*>
             at /rustc/3c3d3c1777041200bb7ed7a65b6562d62899778c\src\libcore\option.rs:314
  12: amethyst_ui::layout::{{impl}}::run
             at C:\Users\Awpteamoose\.cargo\git\checkouts\amethyst-fedb0a1032a075ce\1274ab4\amethyst_ui\src\layout.rs:217
  13: shred::system::{{impl}}::run_now<amethyst_ui::layout::UiTransformSystem>
             at C:\Users\Awpteamoose\.cargo\registry\src\github.com-1ecc6299db9ec823\shred-0.7.2\src\system.rs:133
  14: shred::dispatch::stage::{{impl}}::execute::{{closure}}
             at C:\Users\Awpteamoose\.cargo\registry\src\github.com-1ecc6299db9ec823\shred-0.7.2\src\dispatch\stage.rs:104
  15: rayon::iter::for_each::{{impl}}::consume_iter::{{closure}}<closure,mut arrayvec::ArrayVec<[alloc::boxed::Box<RunNow>; 5]>*,core::slice::IterMut<arrayvec::ArrayVec<[alloc::boxed::Box<RunNow>; 5]>>>
             at C:\Users\Awpteamoose\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-1.0.3\src\iter\for_each.rs:49
  16: core::slice::{{impl}}::fold<arrayvec::ArrayVec<[alloc::boxed::Box<RunNow>; 5]>,(),closure>
             at /rustc/3c3d3c1777041200bb7ed7a65b6562d62899778c\src\libcore\slice\mod.rs:3150
  17: rayon::iter::for_each::{{impl}}::consume_iter<closure,mut arrayvec::ArrayVec<[alloc::boxed::Box<RunNow>; 5]>*,core::slice::IterMut<arrayvec::ArrayVec<[alloc::boxed::Box<RunNow>; 5]>>>
             at C:\Users\Awpteamoose\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-1.0.3\src\iter\for_each.rs:49
  18: rayon::iter::plumbing::Producer::fold_with<rayon::slice::IterMutProducer<arrayvec::ArrayVec<[alloc::boxed::Box<RunNow>; 5]>>,rayon::iter::for_each::ForEachConsumer<closure>>
             at C:\Users\Awpteamoose\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-1.0.3\src\iter\plumbing\mod.rs:108
  19: rayon::iter::plumbing::bridge_producer_consumer::helper<rayon::slice::IterMutProducer<arrayvec::ArrayVec<[alloc::boxed::Box<RunNow>; 5]>>,rayon::iter::for_each::ForEachConsumer<closure>>
             at C:\Users\Awpteamoose\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-1.0.3\src\iter\plumbing\mod.rs:418
  20: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}<rayon::slice::IterMutProducer<arrayvec::ArrayVec<[alloc::boxed::Box<RunNow>; 5]>>,rayon::iter::for_each::ForEachConsumer<closure>>
             at C:\Users\Awpteamoose\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-1.0.3\src\iter\plumbing\mod.rs:410
  21: rayon_core::join::join_context::{{closure}}::{{closure}}<closure,closure,(),()>
             at C:\Users\Awpteamoose\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\join\mod.rs:128
  22: std::panic::{{impl}}::call_once<(),closure>
             at /rustc/3c3d3c1777041200bb7ed7a65b6562d62899778c\src\libstd\panic.rs:309
  23: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
             at /rustc/3c3d3c1777041200bb7ed7a65b6562d62899778c\src\libstd\panicking.rs:293
  24: panic_abort::__rust_maybe_catch_panic
             at /rustc/3c3d3c1777041200bb7ed7a65b6562d62899778c\/src\libpanic_abort\lib.rs:29
  25: std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
             at /rustc/3c3d3c1777041200bb7ed7a65b6562d62899778c\src\libstd\panicking.rs:272
  26: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
             at /rustc/3c3d3c1777041200bb7ed7a65b6562d62899778c\src\libstd\panic.rs:388
  27: rayon_core::unwind::halt_unwinding<closure,()>
             at C:\Users\Awpteamoose\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\unwind.rs:18
  28: rayon_core::join::join_context::{{closure}}<closure,closure,(),()>
             at C:\Users\Awpteamoose\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\join\mod.rs:128
  29: rayon_core::registry::in_worker<closure,((), ())>
             at C:\Users\Awpteamoose\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\registry.rs:705
  30: rayon_core::join::join_context<closure,closure,(),()>
             at C:\Users\Awpteamoose\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\join\mod.rs:116
  31: rayon::iter::plumbing::bridge_producer_consumer::helper<rayon::slice::IterMutProducer<arrayvec::ArrayVec<[alloc::boxed::Box<RunNow>; 5]>>,rayon::iter::for_each::ForEachConsumer<closure>>
             at C:\Users\Awpteamoose\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-1.0.3\src\iter\plumbing\mod.rs:409
  32: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}<rayon::slice::IterMutProducer<arrayvec::ArrayVec<[alloc::boxed::Box<RunNow>; 5]>>,rayon::iter::for_each::ForEachConsumer<closure>>
             at C:\Users\Awpteamoose\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-1.0.3\src\iter\plumbing\mod.rs:413
  33: rayon_core::join::join_context::{{closure}}::{{closure}}<closure,closure,(),()>
             at C:\Users\Awpteamoose\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\join\mod.rs:122
  34: rayon_core::job::{{impl}}::execute::{{closure}}<rayon_core::latch::SpinLatch,closure,()>
             at C:\Users\Awpteamoose\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\job.rs:113
  35: std::panic::{{impl}}::call_once<(),closure>
             at /rustc/3c3d3c1777041200bb7ed7a65b6562d62899778c\src\libstd\panic.rs:309
  36: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
             at /rustc/3c3d3c1777041200bb7ed7a65b6562d62899778c\src\libstd\panicking.rs:293
  37: panic_abort::__rust_maybe_catch_panic
             at /rustc/3c3d3c1777041200bb7ed7a65b6562d62899778c\/src\libpanic_abort\lib.rs:29
  38: std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
             at /rustc/3c3d3c1777041200bb7ed7a65b6562d62899778c\src\libstd\panicking.rs:272
  39: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
             at /rustc/3c3d3c1777041200bb7ed7a65b6562d62899778c\src\libstd\panic.rs:388
  40: rayon_core::unwind::halt_unwinding<closure,()>
             at C:\Users\Awpteamoose\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\unwind.rs:18
  41: rayon_core::job::{{impl}}::execute<rayon_core::latch::SpinLatch,closure,()>
             at C:\Users\Awpteamoose\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\job.rs:113
  42: rayon_core::job::JobRef::execute
             at C:\Users\Awpteamoose\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\job.rs:60
  43: rayon_core::registry::WorkerThread::execute
             at C:\Users\Awpteamoose\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\registry.rs:584
  44: rayon_core::registry::WorkerThread::wait_until_cold<rayon_core::latch::CountLatch>
             at C:\Users\Awpteamoose\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\registry.rs:568
  45: rayon_core::registry::WorkerThread::wait_until<rayon_core::latch::CountLatch>
             at C:\Users\Awpteamoose\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\registry.rs:544
  46: rayon_core::registry::main_loop
             at C:\Users\Awpteamoose\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\registry.rs:666
  47: rayon_core::registry::{{impl}}::new::{{closure}}
             at C:\Users\Awpteamoose\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\registry.rs:135
error: process didn't exit successfully: `target\debug\game.exe` (exit code: 0xc000001d, STATUS_ILLEGAL_INSTRUCTION)
```

**Comment by torkleyy** [comment]
This is the line:

https://github.com/amethyst/amethyst/blob/877e5412db486a9d13a4a523e1ee1a19edba2f12/amethyst_ui/src/layout.rs#L220
