### ISSUE TITLE
[BUG] Rendy example crashes with too much memory

### ISSUE THREAD

**Issue by Dispersia** [amethyst/amethyst#1554]
## Description

 When running the rendy example with latest rendy/amethyst on windows, in debug the CPU spikes to near 100% and uses nearly 2gb of memory, while in release the GPU spikes to 100% and memory is ~1700mb.

## Reproduction Steps

 Run Rendy Example on windows with vulkan (cargo run --example rendy --features="gltf vulkan")

## Screenshots and Logs

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Ok(())`,
 right: `Err(ErrorDeviceLost)`', C:\Users\Computer\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-vulkan-0.1.0\src\lib.rs:765:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Size(2304) is still used', C:\Users\Computer\Desktop\rendy\memory\src\allocator\dynamic.rs:382:13
stack backtrace:
   0:     0x7ff7ddbfac2d - std::sys::windows::backtrace::set_frames
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libstd\sys\windows\backtrace\mod.rs:94
   1:     0x7ff7ddbfac2d - std::sys::windows::backtrace::unwind_backtrace
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libstd\sys\windows\backtrace\mod.rs:81
   2:     0x7ff7ddbfac2d - std::sys_common::backtrace::_print
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libstd\sys_common\backtrace.rs:70
   3:     0x7ff7ddbfe07d - std::sys_common::backtrace::print
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libstd\sys_common\backtrace.rs:58
   4:     0x7ff7ddbfe07d - std::panicking::default_hook::{{closure}}
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libstd\panicking.rs:200
   5:     0x7ff7ddbfdd00 - std::panicking::default_hook
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libstd\panicking.rs:215
   6:     0x7ff7ddbfe90f - std::panicking::rust_panic_with_hook
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libstd\panicking.rs:478
   7:     0x7ff7ddbfe443 - std::panicking::continue_panic_fmt
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libstd\panicking.rs:385
   8:     0x7ff7ddbfe391 - std::panicking::begin_panic_fmt
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libstd\panicking.rs:340
   9:     0x7ff7dccb0c06 - rendy_memory::allocator::dynamic::DynamicAllocator<gfx_backend_vulkan::Backend>::dispose<gfx_backend_vulkan::Backend>
                               at <::std::macros::panic macros>:8
  10:     0x7ff7dd1ec2dd - rendy_memory::heaps::memory_type::MemoryType<gfx_backend_vulkan::Backend>::dispose<gfx_backend_vulkan::Backend>
                               at C:\Users\Computer\Desktop\rendy\memory\src\heaps\memory_type.rs:142
  11:     0x7ff7dd0f8222 - rendy_memory::heaps::Heaps<gfx_backend_vulkan::Backend>::dispose<gfx_backend_vulkan::Backend>
                               at C:\Users\Computer\Desktop\rendy\memory\src\heaps\mod.rs:202
  12:     0x7ff7dcca7328 - rendy_factory::factory::{{impl}}::drop<gfx_backend_vulkan::Backend>
                               at C:\Users\Computer\Desktop\rendy\factory\src\factory.rs:127
  13:     0x7ff7dcbb0d1e - core::ptr::real_drop_in_place<rendy_factory::factory::Factory<gfx_backend_vulkan::Backend>>
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\src\libcore\ptr.rs:193
  14:     0x7ff7ddaf8bd0 - core::ptr::real_drop_in_place<alloc::boxed::Box<Resource>>
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\src\libcore\ptr.rs:193
  15:     0x7ff7ddaf94c2 - core::ptr::real_drop_in_place<core::cell::UnsafeCell<alloc::boxed::Box<Resource>>>
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\src\libcore\ptr.rs:193
  16:     0x7ff7ddafa506 - core::ptr::real_drop_in_place<shred::cell::TrustCell<alloc::boxed::Box<Resource>>>
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\src\libcore\ptr.rs:193
  17:     0x7ff7ddaf8df6 - core::ptr::real_drop_in_place<(shred::res::ResourceId, shred::cell::TrustCell<alloc::boxed::Box<Resource>>)>
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\src\libcore\ptr.rs:193
  18:     0x7ff7ddafc0f6 - core::ptr::drop_in_place
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\src\libcore\ptr.rs:183
  19:     0x7ff7ddafc0f6 - std::collections::hash::table::RawTable<shred::res::ResourceId, shred::cell::TrustCell<alloc::boxed::Box<Resource>>>::rev_drop_buckets<shred::res::ResourceId,shred::cell::TrustCell<alloc::boxed::Box<Resource>>>
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\src\libstd\collections\hash\table.rs:837
  20:     0x7ff7ddafe03e - std::collections::hash::table::{{impl}}::drop<shred::res::ResourceId,shred::cell::TrustCell<alloc::boxed::Box<Resource>>>
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\src\libstd\collections\hash\table.rs:1120
  21:     0x7ff7dcb8b802 - core::ptr::real_drop_in_place<std::collections::hash::table::RawTable<shred::res::ResourceId, shred::cell::TrustCell<alloc::boxed::Box<Resource>>>>
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\src\libcore\ptr.rs:193
  22:     0x7ff7dcb80332 - core::ptr::real_drop_in_place<std::collections::hash::map::HashMap<shred::res::ResourceId, shred::cell::TrustCell<alloc::boxed::Box<Resource>>, core::hash::BuildHasherDefault<fxhash::FxHasher>>>
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\src\libcore\ptr.rs:193
  23:     0x7ff7dcbaf532 - core::ptr::real_drop_in_place<shred::res::Resources>
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\src\libcore\ptr.rs:193
  24:     0x7ff7dcbacee2 - core::ptr::real_drop_in_place<specs::world::World>
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\src\libcore\ptr.rs:193
  25:     0x7ff7dcba964e - core::ptr::real_drop_in_place<amethyst::app::CoreApplication<amethyst::game_data::GameData, amethyst::state_event::StateEvent, amethyst::state_event::StateEventReader>>
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\src\libcore\ptr.rs:193
  26:     0x7ff7dcc04b4d - rendy::main
                               at C:\Users\Computer\Desktop\amethyst\examples\rendy\main.rs:580
  27:     0x7ffc9d5b102f - <unknown>
  28:     0x7ffc9d5b3535 - is_exception_typeof
  29:     0x7ffc9d5bbc13 - _C_specific_handler
  30:     0x7ffc9d5b2f8c - is_exception_typeof
  31:     0x7ffc9d5bc0d0 - _CxxFrameHandler3
  32:     0x7ffcc013f85c - _chkstk
  33:     0x7ffcc00ae23f - RtlUnwindEx
  34:     0x7ffc9d5bbf38 - _C_specific_handler
  35:     0x7ffc9d5b2628 - is_exception_typeof
  36:     0x7ffc9d5b2982 - is_exception_typeof
  37:     0x7ffc9d5b3092 - is_exception_typeof
  38:     0x7ffc9d5bc0d0 - _CxxFrameHandler3
  39:     0x7ffcc013f7dc - _chkstk
  40:     0x7ffcc00ad855 - RtlWalkFrameChain
  41:     0x7ffcc00abe99 - RtlRaiseException
  42:     0x7ffcbc8ca387 - RaiseException
  43:     0x7ffc9d5b480c - CxxThrowException
  44:     0x7ff7ddc02bb7 - panic_unwind::imp::panic
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libpanic_unwind\seh.rs:281
  45:     0x7ff7ddc02bb7 - panic_unwind::__rust_start_panic
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libpanic_unwind\lib.rs:103
  46:     0x7ff7ddbfeae7 - std::panicking::rust_panic
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libstd\panicking.rs:527
  47:     0x7ff7ddbfe9bd - std::panicking::rust_panic_with_hook
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libstd\panicking.rs:498
  48:     0x7ff7ddbfe443 - std::panicking::continue_panic_fmt
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libstd\panicking.rs:385
  49:     0x7ff7ddbfe391 - std::panicking::begin_panic_fmt
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libstd\panicking.rs:340
  50:     0x7ff7dd107999 - gfx_backend_vulkan::{{impl}}::submit<gfx_backend_vulkan::command::CommandBuffer,core::iter::adapters::Map<core::option::IntoIter<rendy_command::buffer::submit::Submit<gfx_backend_vulkan::Backend, rendy_command::buffer::usage::NoSimultaneousUse, rendy_command::buffer::level::PrimaryLevel, rendy_command::buffer::usage::OutsideRenderPass>>, closure>,gfx_backend_vulkan::native::Semaphore,core::iter::adapters::Map<core::iter::adapters::Cloned<core::slice::Iter<(gfx_backend_vulkan::native::Semaphore*, gfx_hal::pso::PipelineStage)>>, closure>,core::iter::adapters::Map<core::iter::adapters::Cloned<core::slice::Iter<gfx_backend_vulkan::native::Semaphore*>>, closure>>
                               at <::std::macros::panic macros>:8
  51:     0x7ff7dd0099ed - rendy_command::family::queue::Queue<gfx_backend_vulkan::Backend>::submit<gfx_backend_vulkan::Backend,gfx_backend_vulkan::native::Semaphore,core::iter::adapters::Cloned<core::slice::Iter<(gfx_backend_vulkan::native::Semaphore*, gfx_hal::pso::PipelineStage)>>,rendy_command::buffer::submit::Submit<gfx_backend_vulkan::Backend, rendy_command::buffer::usage::NoSimultaneousUse, rendy_command::buffer::level::PrimaryLevel, rendy_command::buffer::usage::OutsideRenderPass>,core::option::Option<rendy_command::buffer::submit::Submit<gfx_backend_vulkan::Backend, rendy_command::buffer::usage::NoSimultaneousUse, rendy_command::buffer::level::PrimaryLevel, rendy_command::buffer::usage::OutsideRenderPass>>,gfx_backend_vulkan::native::Semaphore,core::iter::adapters::Cloned<core::slice::Iter<gfx_backend_vulkan::native::Semaphore*>>,core::option::Option<rendy_command::family::submission::Submission<gfx_backend_vulkan::Backend, core::iter::adapters::Cloned<core::slice::Iter<(gfx_backend_vulkan::native::Semaphore*, gfx_hal::pso::PipelineStage)>>, core::option::Option<rendy_command::buffer::submit::Submit<gfx_backend_vulkan::Backend, rendy_command::buffer::usage::NoSimultaneousUse, rendy_command::buffer::level::PrimaryLevel, rendy_command::buffer::usage::OutsideRenderPass>>, core::iter::adapters::Cloned<core::slice::Iter<gfx_backend_vulkan::native::Semaphore*>>>>>
                               at C:\Users\Computer\Desktop\rendy\command\src\family\queue.rs:80
  52:     0x7ff7dd0fc6b9 - rendy_graph::node::render::pass::{{impl}}::run<gfx_backend_vulkan::Backend,shred::res::Resources>
                               at C:\Users\Computer\Desktop\rendy\graph\src\node\render\pass.rs:758
  53:     0x7ff7dc8e6fb9 - rendy_graph::graph::Graph<gfx_backend_vulkan::Backend, shred::res::Resources>::run<gfx_backend_vulkan::Backend,shred::res::Resources>
                               at C:\Users\Computer\Desktop\rendy\graph\src\graph\mod.rs:172
  54:     0x7ff7dd132cee - amethyst_rendy::system::RendererSystem<gfx_backend_vulkan::Backend, rendy::ExampleGraph>::run_graph<gfx_backend_vulkan::Backend,rendy::ExampleGraph>
                               at C:\Users\Computer\Desktop\amethyst\amethyst_rendy\src\system.rs:176
  55:     0x7ff7dd1312cf - amethyst_rendy::system::{{impl}}::run_now<gfx_backend_vulkan::Backend,rendy::ExampleGraph>
                               at C:\Users\Computer\Desktop\amethyst\amethyst_rendy\src\system.rs:195
  56:     0x7ff7ddb0e6b0 - shred::dispatch::dispatcher::Dispatcher::dispatch_thread_local
                               at C:\Users\Computer\.cargo\registry\src\github.com-1ecc6299db9ec823\shred-0.7.2\src\dispatch\dispatcher.rs:111
  57:     0x7ff7ddb0e4cb - shred::dispatch::dispatcher::Dispatcher::dispatch
                               at C:\Users\Computer\.cargo\registry\src\github.com-1ecc6299db9ec823\shred-0.7.2\src\dispatch\dispatcher.rs:68
  58:     0x7ff7dd21782f - amethyst::game_data::GameData::update
                               at C:\Users\Computer\Desktop\amethyst\src\game_data.rs:42
  59:     0x7ff7dc9001cc - amethyst::state::{{impl}}::update<rendy::Example<gfx_backend_vulkan::Backend>>
                               at C:\Users\Computer\Desktop\amethyst\src\state.rs:321
  60:     0x7ff7dcab1139 - amethyst::state::StateMachine<amethyst::game_data::GameData, amethyst::state_event::StateEvent>::update<amethyst::game_data::GameData,amethyst::state_event::StateEvent>
                               at C:\Users\Computer\Desktop\amethyst\src\state.rs:411
  61:     0x7ff7dc9fe757 - amethyst::app::CoreApplication<amethyst::game_data::GameData, amethyst::state_event::StateEvent, amethyst::state_event::StateEventReader>::advance_frame<amethyst::game_data::GameData,amethyst::state_event::StateEvent,amethyst::state_event::StateEventReader>
                               at C:\Users\Computer\Desktop\amethyst\src\app.rs:357
  62:     0x7ff7dc9fefca - amethyst::app::CoreApplication<amethyst::game_data::GameData, amethyst::state_event::StateEvent, amethyst::state_event::StateEventReader>::run<amethyst::game_data::GameData,amethyst::state_event::StateEvent,amethyst::state_event::StateEventReader>
                               at C:\Users\Computer\Desktop\amethyst\src\app.rs:226
  63:     0x7ff7dcc03f71 - rendy::main
                               at C:\Users\Computer\Desktop\amethyst\examples\rendy\main.rs:578
  64:     0x7ff7dceb14bf - std::rt::lang_start::{{closure}}<core::result::Result<(), amethyst_error::Error>>
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\src\libstd\rt.rs:64
  65:     0x7ff7ddbfe286 - std::rt::lang_start_internal::{{closure}}
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libstd\rt.rs:49
  66:     0x7ff7ddbfe286 - std::panicking::try::do_call<closure,i32>
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libstd\panicking.rs:297
  67:     0x7ff7ddc02ad1 - panic_unwind::__rust_maybe_catch_panic
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libpanic_unwind\lib.rs:87
  68:     0x7ff7ddbfec41 - std::panicking::try
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libstd\panicking.rs:276
  69:     0x7ff7ddbfec41 - std::panic::catch_unwind
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libstd\panic.rs:388
  70:     0x7ff7ddbfec41 - std::rt::lang_start_internal
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libstd\rt.rs:48
  71:     0x7ff7dceb149a - std::rt::lang_start<core::result::Result<(), amethyst_error::Error>>
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\src\libstd\rt.rs:64
  72:     0x7ff7dcc04ccf - main
  73:     0x7ff7de332dd3 - invoke_main
                               at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  74:     0x7ff7de332dd3 - __scrt_common_main_seh
                               at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  75:     0x7ffcbf6c4033 - BaseThreadInitThunk
  76:     0x7ffcc0113690 - RtlUserThreadStart
thread panicked while panicking. aborting.
error: process didn't exit successfully: `target\debug\examples\rendy.exe` (exit code: 0xc000001d, STATUS_ILLEGAL_INSTRUCTION)
```

## Your Environment

1. Windows 10, i7-6700, 32gb RAM, Intel HD Graphics 530 (integrated GPU)
2. Version: Master, Rendy: Master

**Comment by torkleyy** [comment]
Tried to reproduce on Fedora + radv, it takes 200-300MB for me, but also 100% CPU.

**Comment by Nalleyer** [comment]
I got a crash too.
# Description
100% cpu but memory usage is ok. crashed after a few seconds.

# output

```
env "RUST_BACKTRACE=1" cargo run --features="vulkan gltf" --example rendy
    Finished dev [unoptimized + debuginfo] target(s) in 0.95s
     Running `target\debug\examples\rendy.exe`
Create spheres
Create lights
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Ok(())`,
 right: `Err(ERROR_DEVICE_LOST)`', C:\Users\qiliuliu\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-vulkan-0.2.3\src\lib.rs:982:9
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys\windows\backtrace\mod.rs:94
   1: std::sys::windows::backtrace::unwind_backtrace
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys\windows\backtrace\mod.rs:81
   2: std::sys_common::backtrace::_print
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys_common\backtrace.rs:70
   3: std::sys_common::backtrace::print
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys_common\backtrace.rs:58
   4: std::panicking::default_hook::{{closure}}
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:200
   5: std::panicking::default_hook
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:215
   6: std::panicking::rust_panic_with_hook
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:478
   7: std::panicking::continue_panic_fmt
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:385
   8: std::panicking::begin_panic_fmt
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:340
   9: gfx_backend_vulkan::{{impl}}::submit<gfx_backend_vulkan::command::CommandBuffer,core::iter::adapters::Map<core::option::IntoIter<rendy_command::buffer::submit::Submit<gfx_backend_vulkan::Backend, rendy_command::buffer::usage::NoSimultaneousUse, rendy_command::buffer::level::PrimaryLevel, rendy_command::buffer::usage::OutsideRenderPass>>, closure>,gfx_backend_vulkan::native::Semaphore,core::iter::adapters::Map<core::iter::adapters::Cloned<core::slice::Iter<(gfx_backend_vulkan::native::Semaphore*, gfx_hal::pso::PipelineStage)>>, closure>,core::iter::adapters::Map<core::iter::adapters::Cloned<core::slice::Iter<gfx_backend_vulkan::native::Semaphore*>>, closure>>
             at <::std::macros::panic macros>:8
  10: rendy_command::family::queue::Queue<gfx_backend_vulkan::Backend>::submit<gfx_backend_vulkan::Backend,gfx_backend_vulkan::native::Semaphore,core::iter::adapters::Cloned<core::slice::Iter<(gfx_backend_vulkan::native::Semaphore*, gfx_hal::pso::PipelineStage)>>,rendy_command::buffer::submit::Submit<gfx_backend_vulkan::Backend, rendy_command::buffer::usage::NoSimultaneousUse, rendy_command::buffer::level::PrimaryLevel, rendy_command::buffer::usage::OutsideRenderPass>,core::option::Option<rendy_command::buffer::submit::Submit<gfx_backend_vulkan::Backend, rendy_command::buffer::usage::NoSimultaneousUse, rendy_command::buffer::level::PrimaryLevel, rendy_command::buffer::usage::OutsideRenderPass>>,gfx_backend_vulkan::native::Semaphore,core::iter::adapters::Cloned<core::slice::Iter<gfx_backend_vulkan::native::Semaphore*>>,core::option::Option<rendy_command::family::submission::Submission<gfx_backend_vulkan::Backend, core::iter::adapters::Cloned<core::slice::Iter<(gfx_backend_vulkan::native::Semaphore*, gfx_hal::pso::PipelineStage)>>, core::option::Option<rendy_command::buffer::submit::Submit<gfx_backend_vulkan::Backend, rendy_command::buffer::usage::NoSimultaneousUse, rendy_command::buffer::level::PrimaryLevel, rendy_command::buffer::usage::OutsideRenderPass>>, core::iter::adapters::Cloned<core::slice::Iter<gfx_backend_vulkan::native::Semaphore*>>>>>
             at C:\Users\qiliuliu\.cargo\registry\src\github.com-1ecc6299db9ec823\rendy-command-0.3.0\src\family\queue.rs:80
  11: rendy_graph::node::render::pass::{{impl}}::run<gfx_backend_vulkan::Backend,shred::res::Resources>
             at C:\Users\qiliuliu\.cargo\registry\src\github.com-1ecc6299db9ec823\rendy-graph-0.3.2\src\node\render\pass.rs:1247
  12: rendy_graph::graph::Graph<gfx_backend_vulkan::Backend, shred::res::Resources>::run<gfx_backend_vulkan::Backend,shred::res::Resources>
             at C:\Users\qiliuliu\.cargo\registry\src\github.com-1ecc6299db9ec823\rendy-graph-0.3.2\src\graph\mod.rs:184
  13: amethyst_rendy::system::RenderingSystem<gfx_backend_vulkan::Backend, rendy::ExampleGraph>::run_graph<gfx_backend_vulkan::Backend,rendy::ExampleGraph>
             at .\amethyst_rendy\src\system.rs:209
  14: amethyst_rendy::system::{{impl}}::run_now<gfx_backend_vulkan::Backend,rendy::ExampleGraph>
             at .\amethyst_rendy\src\system.rs:228
  15: shred::dispatch::dispatcher::Dispatcher::dispatch_thread_local
             at C:\Users\qiliuliu\.cargo\registry\src\github.com-1ecc6299db9ec823\shred-0.7.2\src\dispatch\dispatcher.rs:111
  16: shred::dispatch::dispatcher::Dispatcher::dispatch
             at C:\Users\qiliuliu\.cargo\registry\src\github.com-1ecc6299db9ec823\shred-0.7.2\src\dispatch\dispatcher.rs:68
  17: amethyst::game_data::GameData::update
             at .\src\game_data.rs:41
  18: amethyst::state::{{impl}}::update<rendy::Example>
             at .\src\state.rs:336
  19: amethyst::state::StateMachine<amethyst::game_data::GameData, amethyst::state_event::StateEvent<amethyst_input::bindings::StringBindings>>::update<amethyst::game_data::GameData,amethyst::state_event::StateEvent<amethyst_input::bindings::StringBindings>>
             at .\src\state.rs:438
  20: amethyst::app::CoreApplication<amethyst::game_data::GameData, amethyst::state_event::StateEvent<amethyst_input::bindings::StringBindings>, amethyst::state_event::StateEventReader<amethyst_input::bindings::StringBindings>>::advance_frame<amethyst::game_data::GameData,amethyst::state_event::StateEvent<amethyst_input::bindings::StringBindings>,amethyst::state_event::StateEventReader<amethyst_input::bindings::StringBindings>>
             at .\src\app.rs:371
  21: amethyst::app::CoreApplication<amethyst::game_data::GameData, amethyst::state_event::StateEvent<amethyst_input::bindings::StringBindings>, amethyst::state_event::StateEventReader<amethyst_input::bindings::StringBindings>>::run<amethyst::game_data::GameData,amethyst::state_event::StateEvent<amethyst_input::bindings::StringBindings>,amethyst::state_event::StateEventReader<amethyst_input::bindings::StringBindings>>
             at .\src\app.rs:235
  22: rendy::main
             at .\examples\rendy\main.rs:655
  23: std::rt::lang_start::{{closure}}<core::result::Result<(), amethyst_error::Error>>
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\libstd\rt.rs:64
  24: std::rt::lang_start_internal::{{closure}}
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\rt.rs:49
  25: std::panicking::try::do_call<closure,i32>
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:297
  26: panic_unwind::__rust_maybe_catch_panic
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libpanic_unwind\lib.rs:87
  27: std::panicking::try
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:276
  28: std::panic::catch_unwind
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panic.rs:388
  29: std::rt::lang_start_internal
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\rt.rs:48
  30: std::rt::lang_start<core::result::Result<(), amethyst_error::Error>>
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\libstd\rt.rs:64
  31: main
  32: invoke_main
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  33: __scrt_common_main_seh
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  34: BaseThreadInitThunk
  35: RtlUserThreadStart
```

# Environment
Windows 10, i7 7700, 24gb memory, hd 630(integrated GPU)

**Comment by Frizi** [comment]
Not stale.

I believe that the 100% CPU usage is legitimately nalgebra trying to calculate positions for all the moving objects. I have no explanation for memory usage though.

Is the memory usage that high in release mode?

**Comment by Dispersia** [comment]
When I first posted, it was a bit less (1700mb) but that still seems like a lot for the example. Unfortunately I no longer have access to the computer that was happening on, and it seems to work fine on my other computers.
