### ISSUE TITLE
[BUG] Crash on Intel GPUs

### ISSUE THREAD

**Issue by Xaeroxe** [amethyst/amethyst#1643]
## Description

All examples crash on Windows 10 Intel HD Graphics chips. They worked previously.

This represents about 10% of Steam users, so we should place at least some priority on working with this chipset.

## Reproduction Steps

Run the following command in the amethyst source folder on Windows 10 with an Intel HD graphics card.

```
cargo run --example renderable --features dx12
```

## What You Expected to Happen

The example opens and runs normally.

## What Actually Happened

The example panics upon opening.

## Screenshots and Logs

<details><summary>Log (Click to expand)</summary>
<p>

```
PS C:\Users\user\amethyst\examples> cargo run --example renderable --features dx12
    Finished dev [unoptimized + debuginfo] target(s) in 0.67s
     Running `C:\Users\user\amethyst\target\debug\examples\renderable.exe`
[INFO][winit::platform::platform::window] Guessed window DPI factor: 1
[INFO][amethyst::app] Initializing Amethyst...
[INFO][amethyst::app] Version: 0.10.0
[INFO][amethyst::app] Platform: x86_64-pc-windows-msvc
[INFO][amethyst::app] Amethyst git commit: d59a5dc67b0eb6cb573ae706eb39d18f1a5c5439
[INFO][amethyst::app] Rustc version: 1.35.0 Stable
[INFO][amethyst::app] Rustc git commit: 3c235d5600393dfe6c36eeed34042efad8d4f26e
[WARN][rendy_factory::factory] Slow safety checks are enabled! Disable them in production by enabling the 'no-slow-safety-checks' feature!
[INFO][rendy_factory::factory] Physical devices:
[
    AdapterInfo {
        name: "Intel(R) HD Graphics 630",
        vendor: 32902,
        device: 22802,
        device_type: DiscreteGpu,
    },
    AdapterInfo {
        name: "Microsoft Basic Render Driver",
        vendor: 5140,
        device: 140,
        device_type: VirtualGpu,
    },
]
[INFO][rendy_factory::factory] Physical device picked: PhysicalDeviceInfo {
    name: "Intel(R) HD Graphics 630",
    features: ROBUST_BUFFER_ACCESS | IMAGE_CUBE_ARRAY | GEOMETRY_SHADER | TESSELLATION_SHADER | MULTI_DRAW_INDIRECT | NON_FILL_POLYGON_MODE | SAMPLER_ANISOTROPY | FORMAT_BC | INSTANCE_RATE | SAMPLER_MIP_LOD_BIAS,
    limits: Limits {
        max_image_1d_size: 16384,
        max_image_2d_size: 16384,
        max_image_3d_size: 2048,
        max_image_cube_size: 16384,
        max_image_array_layers: 2048,
        max_texel_elements: 0,
        max_uniform_buffer_range: 0,
        max_storage_buffer_range: 0,
        max_push_constants_size: 0,
        max_memory_allocation_count: 0,
        max_sampler_allocation_count: 0,
        max_bound_descriptor_sets: 0,
        max_per_stage_descriptor_samplers: 0,
        max_per_stage_descriptor_uniform_buffers: 0,
        max_per_stage_descriptor_storage_buffers: 0,
        max_per_stage_descriptor_sampled_images: 0,
        max_per_stage_descriptor_storage_images: 0,
        max_per_stage_descriptor_input_attachments: 0,
        max_per_stage_resources: 0,
        max_descriptor_set_samplers: 0,
        max_descriptor_set_uniform_buffers: 0,
        max_descriptor_set_uniform_buffers_dynamic: 0,
        max_descriptor_set_storage_buffers: 0,
        max_descriptor_set_storage_buffers_dynamic: 0,
        max_descriptor_set_sampled_images: 0,
        max_descriptor_set_storage_images: 0,
        max_descriptor_set_input_attachments: 0,
        max_vertex_input_attributes: 32,
        max_vertex_input_bindings: 31,
        max_vertex_input_attribute_offset: 255,
        max_vertex_input_binding_stride: 2048,
        max_vertex_output_components: 16,
        max_patch_size: 0,
        max_geometry_shader_invocations: 0,
        max_geometry_input_components: 0,
        max_geometry_output_components: 0,
        max_geometry_output_vertices: 0,
        max_geometry_total_output_components: 0,
        max_fragment_input_components: 0,
        max_fragment_output_attachments: 0,
        max_fragment_dual_source_attachments: 0,
        max_fragment_combined_output_resources: 0,
        max_compute_shared_memory_size: 0,
        max_compute_work_group_count: [
            1024,
            1024,
            64,
        ],
        max_compute_work_group_invocations: 0,
        max_compute_work_group_size: [
            1024,
            1,
            1,
        ],
        max_draw_indexed_index_value: 0,
        max_draw_indirect_count: 0,
        max_sampler_lod_bias: 0.0,
        max_sampler_anisotropy: 16.0,
        max_viewports: 16,
        max_viewport_dimensions: [
            32767,
            32767,
        ],
        max_framebuffer_extent: Extent {
            width: 4096,
            height: 4096,
            depth: 1,
        },
        min_memory_map_alignment: 0,
        buffer_image_granularity: 1,
        min_texel_buffer_offset_alignment: 1,
        min_uniform_buffer_offset_alignment: 256,
        min_storage_buffer_offset_alignment: 1,
        framebuffer_color_samples_count: 5,
        framebuffer_depth_samples_count: 5,
        framebuffer_stencil_samples_count: 5,
        max_color_attachments: 8,
        standard_sample_locations: false,
        optimal_buffer_copy_offset_alignment: 512,
        optimal_buffer_copy_pitch_alignment: 256,
        non_coherent_atom_size: 1,
        min_vertex_input_binding_stride_alignment: 1,
    },
}
[INFO][rendy_util::wrap] Slow safety checks are enabled! You can disable them in production by enabling the 'no-slow-safety-checks' feature!
[INFO][rendy_factory::factory] Queues: [
    (
        FamilyId {
            index: 0,
            device: DeviceId {
                id: 0,
                instance: InstanceId {
                    id: 0,
                },
            },
        },
        1,
    ),
]
[INFO][rendy_factory::factory] Heaps: [
    3727446220,
]
Types: [
    (
        DEVICE_LOCAL,
        0,
        HeapsConfig {
            linear: None,
            dynamic: Some(
                DynamicConfig {
                    block_size_granularity: 256,
                    max_chunk_size: 33554432,
                    min_device_allocation: 1048576,
                },
            ),
        },
    ),
    (
        DEVICE_LOCAL | CPU_VISIBLE | COHERENT | CPU_CACHED,
        0,
        HeapsConfig {
            linear: Some(
                LinearConfig {
                    linear_size: 134217728,
                },
            ),
            dynamic: Some(
                DynamicConfig {
                    block_size_granularity: 256,
                    max_chunk_size: 33554432,
                    min_device_allocation: 1048576,
                },
            ),
        },
    ),
    (
        DEVICE_LOCAL | CPU_VISIBLE | COHERENT | CPU_CACHED,
        0,
        HeapsConfig {
            linear: Some(
                LinearConfig {
                    linear_size: 134217728,
                },
            ),
            dynamic: Some(
                DynamicConfig {
                    block_size_granularity: 256,
                    max_chunk_size: 33554432,
                    min_device_allocation: 1048576,
                },
            ),
        },
    ),
]
[INFO][rendy_memory::allocator::dynamic] Create new allocator: type: 'MemoryTypeId(0)', properties: 'DEVICE_LOCAL' config: 'DynamicConfig {
    block_size_granularity: 256,
    max_chunk_size: 33554432,
    min_device_allocation: 1048576,
}'
[INFO][rendy_memory::allocator::linear] Create new 'linear' allocator: type: 'MemoryTypeId(1)', properties: 'DEVICE_LOCAL | CPU_VISIBLE | COHERENT | CPU_CACHED' config: 'LinearConfig {
    linear_size: 134217728,
}'
[INFO][rendy_memory::allocator::dynamic] Create new allocator: type: 'MemoryTypeId(1)', properties: 'DEVICE_LOCAL | CPU_VISIBLE | COHERENT | CPU_CACHED' config: 'DynamicConfig {
    block_size_granularity: 256,
    max_chunk_size: 33554432,
    min_device_allocation: 1048576,
}'
[INFO][rendy_memory::allocator::linear] Create new 'linear' allocator: type: 'MemoryTypeId(2)', properties: 'DEVICE_LOCAL | CPU_VISIBLE | COHERENT | CPU_CACHED' config: 'LinearConfig {
    linear_size: 134217728,
}'
[INFO][rendy_memory::allocator::dynamic] Create new allocator: type: 'MemoryTypeId(2)', properties: 'DEVICE_LOCAL | CPU_VISIBLE | COHERENT | CPU_CACHED' config: 'DynamicConfig {
    block_size_granularity: 256,
    max_chunk_size: 33554432,
    min_device_allocation: 1048576,
}'
thread '<unnamed>' panicked at 'Failed to create glyph texture: ErrorMessage { msg: "Format R8Srgb is not supported and no suitable conversion found." }', src\libcore\result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: process didn't exit successfully: `C:\Users\user\amethyst\target\debug\examples\renderable.exe` (exit code: 101)
```

</p>
</details>

## Your Environment

1. Operating System: Windows
2. Operating System Version: 10
3. Version of Amethyst: Master branch, commit 4800ac5a

**Comment by torkleyy** [comment]
Ah, DirectX 12 isn't working yet. Could you try using Vulkan?

**Comment by Xaeroxe** [comment]
Ok, works fine on vulkan, though the renderable example spins on the wrong axis.

**Comment by BrianMWest** [comment]
I get this problem on macOS (MBP 2017) with metal as well in master branch ref `1dd1417a7e7d2e769a48056b166f81ba2a008036`.

```
cargo run --example renderable --features metal
```

Log:
```
[INFO][amethyst::app] Initializing Amethyst...
[INFO][amethyst::app] Version: 0.10.0
[INFO][amethyst::app] Platform: x86_64-apple-darwin
[INFO][amethyst::app] Amethyst git commit: 1dd1417a7e7d2e769a48056b166f81ba2a008036
[INFO][amethyst::app] Rustc version: 1.36.0-nightly Nightly
[INFO][amethyst::app] Rustc git commit: 5187be620c76a313a19b9b596e1bce3a80a345dd
[WARN][rendy_factory::factory] Slow safety checks are enabled! Disable them in production by enabling the 'no-slow-safety-checks' feature!
[INFO][rendy_factory::factory] Physical devices:
[
    AdapterInfo {
        name: "AMD Radeon Pro 560",
        vendor: 0,
        device: 0,
        device_type: DiscreteGpu,
    },
    AdapterInfo {
        name: "Intel(R) HD Graphics 630",
        vendor: 0,
        device: 0,
        device_type: IntegratedGpu,
    },
]
[INFO][rendy_factory::factory] Physical device picked: PhysicalDeviceInfo {
    name: "AMD Radeon Pro 560",
    features: ROBUST_BUFFER_ACCESS | DUAL_SRC_BLENDING | DRAW_INDIRECT_FIRST_INSTANCE | DEPTH_CLAMP | NON_FILL_POLYGON_MODE | SAMPLER_ANISOTROPY | FORMAT_BC | PRECISE_OCCLUSION_QUERY | VERTEX_STORES_AND_ATOMICS | FRAGMENT_STORES_AND_ATOMICS | SHADER_STORAGE_BUFFER_ARRAY_DYNAMIC_INDEXING | SHADER_CLIP_DISTANCE | SEPARATE_STENCIL_REF_VALUES | INSTANCE_RATE,
    limits: Limits {
        max_image_1d_size: 16384,
        max_image_2d_size: 16384,
        max_image_3d_size: 2048,
        max_image_cube_size: 16384,
        max_image_array_layers: 2048,
        max_texel_elements: 268435456,
        max_uniform_buffer_range: 1073741824,
        max_storage_buffer_range: 1073741824,
        max_push_constants_size: 4096,
        max_memory_allocation_count: 18446744073709551615,
        max_sampler_allocation_count: 18446744073709551615,
        max_bound_descriptor_sets: 256,
        max_per_stage_descriptor_samplers: 16,
        max_per_stage_descriptor_uniform_buffers: 31,
        max_per_stage_descriptor_storage_buffers: 31,
        max_per_stage_descriptor_sampled_images: 128,
        max_per_stage_descriptor_storage_images: 128,
        max_per_stage_descriptor_input_attachments: 128,
        max_per_stage_resources: 256,
        max_descriptor_set_samplers: 0,
        max_descriptor_set_uniform_buffers: 0,
        max_descriptor_set_uniform_buffers_dynamic: 0,
        max_descriptor_set_storage_buffers: 0,
        max_descriptor_set_storage_buffers_dynamic: 0,
        max_descriptor_set_sampled_images: 0,
        max_descriptor_set_storage_images: 0,
        max_descriptor_set_input_attachments: 0,
        max_vertex_input_attributes: 31,
        max_vertex_input_bindings: 31,
        max_vertex_input_attribute_offset: 255,
        max_vertex_input_binding_stride: 256,
        max_vertex_output_components: 16,
        max_patch_size: 0,
        max_geometry_shader_invocations: 0,
        max_geometry_input_components: 0,
        max_geometry_output_components: 0,
        max_geometry_output_vertices: 0,
        max_geometry_total_output_components: 0,
        max_fragment_input_components: 0,
        max_fragment_output_attachments: 0,
        max_fragment_dual_source_attachments: 0,
        max_fragment_combined_output_resources: 0,
        max_compute_shared_memory_size: 0,
        max_compute_work_group_count: [
            16,
            16,
            16,
        ],
        max_compute_work_group_invocations: 0,
        max_compute_work_group_size: [
            64,
            64,
            64,
        ],
        max_draw_indexed_index_value: 0,
        max_draw_indirect_count: 0,
        max_sampler_lod_bias: 0.0,
        max_sampler_anisotropy: 16.0,
        max_viewports: 1,
        max_viewport_dimensions: [
            16384,
            16384,
        ],
        max_framebuffer_extent: Extent {
            width: 16384,
            height: 16384,
            depth: 2048,
        },
        min_memory_map_alignment: 0,
        buffer_image_granularity: 1,
        min_texel_buffer_offset_alignment: 256,
        min_uniform_buffer_offset_alignment: 256,
        min_storage_buffer_offset_alignment: 256,
        framebuffer_color_samples_count: 5,
        framebuffer_depth_samples_count: 5,
        framebuffer_stencil_samples_count: 5,
        max_color_attachments: 4,
        standard_sample_locations: false,
        optimal_buffer_copy_offset_alignment: 256,
        optimal_buffer_copy_pitch_alignment: 4,
        non_coherent_atom_size: 4,
        min_vertex_input_binding_stride_alignment: 4,
    },
}
[INFO][rendy_util::wrap] Slow safety checks are enabled! You can disable them in production by enabling the 'no-slow-safety-checks' feature!
[INFO][rendy_factory::factory] Queues: [
    (
        FamilyId {
            index: 0,
            device: DeviceId {
                id: 0,
                instance: InstanceId {
                    id: 0,
                },
            },
        },
        1,
    ),
]
[INFO][rendy_factory::factory] Heaps: [
    18446744073709551615,
    1073741824,
]
Types: [
    (
        DEVICE_LOCAL,
        0,
        HeapsConfig {
            linear: None,
            dynamic: Some(
                DynamicConfig {
                    block_size_granularity: 256,
                    max_chunk_size: 33554432,
                    min_device_allocation: 1048576,
                },
            ),
        },
    ),
    (
        CPU_VISIBLE | COHERENT,
        1,
        HeapsConfig {
            linear: Some(
                LinearConfig {
                    linear_size: 67108864,
                },
            ),
            dynamic: Some(
                DynamicConfig {
                    block_size_granularity: 256,
                    max_chunk_size: 8388608,
                    min_device_allocation: 1048576,
                },
            ),
        },
    ),
    (
        DEVICE_LOCAL | CPU_VISIBLE,
        1,
        HeapsConfig {
            linear: Some(
                LinearConfig {
                    linear_size: 67108864,
                },
            ),
            dynamic: Some(
                DynamicConfig {
                    block_size_granularity: 256,
                    max_chunk_size: 8388608,
                    min_device_allocation: 1048576,
                },
            ),
        },
    ),
    (
        DEVICE_LOCAL | CPU_VISIBLE | CPU_CACHED,
        1,
        HeapsConfig {
            linear: Some(
                LinearConfig {
                    linear_size: 67108864,
                },
            ),
            dynamic: Some(
                DynamicConfig {
                    block_size_granularity: 256,
                    max_chunk_size: 8388608,
                    min_device_allocation: 1048576,
                },
            ),
        },
    ),
]
[INFO][rendy_memory::allocator::dynamic] Create new allocator: type: 'MemoryTypeId(0)', properties: 'DEVICE_LOCAL' config: 'DynamicConfig {
    block_size_granularity: 256,
    max_chunk_size: 33554432,
    min_device_allocation: 1048576,
}'
[INFO][rendy_memory::allocator::linear] Create new 'linear' allocator: type: 'MemoryTypeId(1)', properties: 'CPU_VISIBLE | COHERENT' config: 'LinearConfig {
    linear_size: 67108864,
}'
[INFO][rendy_memory::allocator::dynamic] Create new allocator: type: 'MemoryTypeId(1)', properties: 'CPU_VISIBLE | COHERENT' config: 'DynamicConfig {
    block_size_granularity: 256,
    max_chunk_size: 8388608,
    min_device_allocation: 1048576,
}'
[INFO][rendy_memory::allocator::linear] Create new 'linear' allocator: type: 'MemoryTypeId(2)', properties: 'DEVICE_LOCAL | CPU_VISIBLE' config: 'LinearConfig {
    linear_size: 67108864,
}'
[INFO][rendy_memory::allocator::dynamic] Create new allocator: type: 'MemoryTypeId(2)', properties: 'DEVICE_LOCAL | CPU_VISIBLE' config: 'DynamicConfig {
    block_size_granularity: 256,
    max_chunk_size: 8388608,
    min_device_allocation: 1048576,
}'
[INFO][rendy_memory::allocator::linear] Create new 'linear' allocator: type: 'MemoryTypeId(3)', properties: 'DEVICE_LOCAL | CPU_VISIBLE | CPU_CACHED' config: 'LinearConfig {
    linear_size: 67108864,
}'
[INFO][rendy_memory::allocator::dynamic] Create new allocator: type: 'MemoryTypeId(3)', properties: 'DEVICE_LOCAL | CPU_VISIBLE | CPU_CACHED' config: 'DynamicConfig {
    block_size_granularity: 256,
    max_chunk_size: 8388608,
    min_device_allocation: 1048576,
}'
thread '<unnamed>' panicked at 'Failed to create glyph texture: ErrorMessage { msg: "Format R8Srgb is not supported and no suitable conversion found." }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by jojolepro** [comment]
Not stole thanks

**Comment by distransient** [comment]
Not confirmed as solved yet.

**Comment by distransient** [comment]
@BrianMWest has this been resolved?

**Comment by khionu** [comment]
This has been marked as Stale three times now, I'm going to close it unless we get further responses.
