### ISSUE TITLE
[Rendy] amethyst_ui currently does not support metal

### ISSUE THREAD

**Issue by jaynus** [amethyst/amethyst#1663]
I get this problem on macOS (MBP 2017) with metal as well in master branch ref `1dd1417a7e7d2e769a48056b166f81ba2a008036`.

```
cargo run --example renderable --features metal
```

Log:
```
[INFO][amethyst::app] Initializing Amethyst...
[INFO][amethyst::app] Version: 0.10.0
[INFO][amethyst::app] Platform: x86_64-apple-darwin
[INFO][amethyst::app] Amethyst git commit: 1dd1417a7e7d2e769a48056b166f81ba2a008036
[INFO][amethyst::app] Rustc version: 1.36.0-nightly Nightly
[INFO][amethyst::app] Rustc git commit: 5187be620c76a313a19b9b596e1bce3a80a345dd
[WARN][rendy_factory::factory] Slow safety checks are enabled! Disable them in production by enabling the 'no-slow-safety-checks' feature!
[INFO][rendy_factory::factory] Physical devices:
[
    AdapterInfo {
        name: "AMD Radeon Pro 560",
        vendor: 0,
        device: 0,
        device_type: DiscreteGpu,
    },
    AdapterInfo {
        name: "Intel(R) HD Graphics 630",
        vendor: 0,
        device: 0,
        device_type: IntegratedGpu,
    },
]
[INFO][rendy_factory::factory] Physical device picked: PhysicalDeviceInfo {
    name: "AMD Radeon Pro 560",
    features: ROBUST_BUFFER_ACCESS | DUAL_SRC_BLENDING | DRAW_INDIRECT_FIRST_INSTANCE | DEPTH_CLAMP | NON_FILL_POLYGON_MODE | SAMPLER_ANISOTROPY | FORMAT_BC | PRECISE_OCCLUSION_QUERY | VERTEX_STORES_AND_ATOMICS | FRAGMENT_STORES_AND_ATOMICS | SHADER_STORAGE_BUFFER_ARRAY_DYNAMIC_INDEXING | SHADER_CLIP_DISTANCE | SEPARATE_STENCIL_REF_VALUES | INSTANCE_RATE,
    limits: Limits {
        max_image_1d_size: 16384,
        max_image_2d_size: 16384,
        max_image_3d_size: 2048,
        max_image_cube_size: 16384,
        max_image_array_layers: 2048,
        max_texel_elements: 268435456,
        max_uniform_buffer_range: 1073741824,
        max_storage_buffer_range: 1073741824,
        max_push_constants_size: 4096,
        max_memory_allocation_count: 18446744073709551615,
        max_sampler_allocation_count: 18446744073709551615,
        max_bound_descriptor_sets: 256,
        max_per_stage_descriptor_samplers: 16,
        max_per_stage_descriptor_uniform_buffers: 31,
        max_per_stage_descriptor_storage_buffers: 31,
        max_per_stage_descriptor_sampled_images: 128,
        max_per_stage_descriptor_storage_images: 128,
        max_per_stage_descriptor_input_attachments: 128,
        max_per_stage_resources: 256,
        max_descriptor_set_samplers: 0,
        max_descriptor_set_uniform_buffers: 0,
        max_descriptor_set_uniform_buffers_dynamic: 0,
        max_descriptor_set_storage_buffers: 0,
        max_descriptor_set_storage_buffers_dynamic: 0,
        max_descriptor_set_sampled_images: 0,
        max_descriptor_set_storage_images: 0,
        max_descriptor_set_input_attachments: 0,
        max_vertex_input_attributes: 31,
        max_vertex_input_bindings: 31,
        max_vertex_input_attribute_offset: 255,
        max_vertex_input_binding_stride: 256,
        max_vertex_output_components: 16,
        max_patch_size: 0,
        max_geometry_shader_invocations: 0,
        max_geometry_input_components: 0,
        max_geometry_output_components: 0,
        max_geometry_output_vertices: 0,
        max_geometry_total_output_components: 0,
        max_fragment_input_components: 0,
        max_fragment_output_attachments: 0,
        max_fragment_dual_source_attachments: 0,
        max_fragment_combined_output_resources: 0,
        max_compute_shared_memory_size: 0,
        max_compute_work_group_count: [
            16,
            16,
            16,
        ],
        max_compute_work_group_invocations: 0,
        max_compute_work_group_size: [
            64,
            64,
            64,
        ],
        max_draw_indexed_index_value: 0,
        max_draw_indirect_count: 0,
        max_sampler_lod_bias: 0.0,
        max_sampler_anisotropy: 16.0,
        max_viewports: 1,
        max_viewport_dimensions: [
            16384,
            16384,
        ],
        max_framebuffer_extent: Extent {
            width: 16384,
            height: 16384,
            depth: 2048,
        },
        min_memory_map_alignment: 0,
        buffer_image_granularity: 1,
        min_texel_buffer_offset_alignment: 256,
        min_uniform_buffer_offset_alignment: 256,
        min_storage_buffer_offset_alignment: 256,
        framebuffer_color_samples_count: 5,
        framebuffer_depth_samples_count: 5,
        framebuffer_stencil_samples_count: 5,
        max_color_attachments: 4,
        standard_sample_locations: false,
        optimal_buffer_copy_offset_alignment: 256,
        optimal_buffer_copy_pitch_alignment: 4,
        non_coherent_atom_size: 4,
        min_vertex_input_binding_stride_alignment: 4,
    },
}
[INFO][rendy_util::wrap] Slow safety checks are enabled! You can disable them in production by enabling the 'no-slow-safety-checks' feature!
[INFO][rendy_factory::factory] Queues: [
    (
        FamilyId {
            index: 0,
            device: DeviceId {
                id: 0,
                instance: InstanceId {
                    id: 0,
                },
            },
        },
        1,
    ),
]
[INFO][rendy_factory::factory] Heaps: [
    18446744073709551615,
    1073741824,
]
Types: [
    (
        DEVICE_LOCAL,
        0,
        HeapsConfig {
            linear: None,
            dynamic: Some(
                DynamicConfig {
                    block_size_granularity: 256,
                    max_chunk_size: 33554432,
                    min_device_allocation: 1048576,
                },
            ),
        },
    ),
    (
        CPU_VISIBLE | COHERENT,
        1,
        HeapsConfig {
            linear: Some(
                LinearConfig {
                    linear_size: 67108864,
                },
            ),
            dynamic: Some(
                DynamicConfig {
                    block_size_granularity: 256,
                    max_chunk_size: 8388608,
                    min_device_allocation: 1048576,
                },
            ),
        },
    ),
    (
        DEVICE_LOCAL | CPU_VISIBLE,
        1,
        HeapsConfig {
            linear: Some(
                LinearConfig {
                    linear_size: 67108864,
                },
            ),
            dynamic: Some(
                DynamicConfig {
                    block_size_granularity: 256,
                    max_chunk_size: 8388608,
                    min_device_allocation: 1048576,
                },
            ),
        },
    ),
    (
        DEVICE_LOCAL | CPU_VISIBLE | CPU_CACHED,
        1,
        HeapsConfig {
            linear: Some(
                LinearConfig {
                    linear_size: 67108864,
                },
            ),
            dynamic: Some(
                DynamicConfig {
                    block_size_granularity: 256,
                    max_chunk_size: 8388608,
                    min_device_allocation: 1048576,
                },
            ),
        },
    ),
]
[INFO][rendy_memory::allocator::dynamic] Create new allocator: type: 'MemoryTypeId(0)', properties: 'DEVICE_LOCAL' config: 'DynamicConfig {
    block_size_granularity: 256,
    max_chunk_size: 33554432,
    min_device_allocation: 1048576,
}'
[INFO][rendy_memory::allocator::linear] Create new 'linear' allocator: type: 'MemoryTypeId(1)', properties: 'CPU_VISIBLE | COHERENT' config: 'LinearConfig {
    linear_size: 67108864,
}'
[INFO][rendy_memory::allocator::dynamic] Create new allocator: type: 'MemoryTypeId(1)', properties: 'CPU_VISIBLE | COHERENT' config: 'DynamicConfig {
    block_size_granularity: 256,
    max_chunk_size: 8388608,
    min_device_allocation: 1048576,
}'
[INFO][rendy_memory::allocator::linear] Create new 'linear' allocator: type: 'MemoryTypeId(2)', properties: 'DEVICE_LOCAL | CPU_VISIBLE' config: 'LinearConfig {
    linear_size: 67108864,
}'
[INFO][rendy_memory::allocator::dynamic] Create new allocator: type: 'MemoryTypeId(2)', properties: 'DEVICE_LOCAL | CPU_VISIBLE' config: 'DynamicConfig {
    block_size_granularity: 256,
    max_chunk_size: 8388608,
    min_device_allocation: 1048576,
}'
[INFO][rendy_memory::allocator::linear] Create new 'linear' allocator: type: 'MemoryTypeId(3)', properties: 'DEVICE_LOCAL | CPU_VISIBLE | CPU_CACHED' config: 'LinearConfig {
    linear_size: 67108864,
}'
[INFO][rendy_memory::allocator::dynamic] Create new allocator: type: 'MemoryTypeId(3)', properties: 'DEVICE_LOCAL | CPU_VISIBLE | CPU_CACHED' config: 'DynamicConfig {
    block_size_granularity: 256,
    max_chunk_size: 8388608,
    min_device_allocation: 1048576,
}'
thread '<unnamed>' panicked at 'Failed to create glyph texture: ErrorMessage { msg: "Format R8Srgb is not supported and no suitable conversion found." }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

_Originally posted by @BrianMWest in https://github.com/amethyst/amethyst/issues/1643#issuecomment-496347768_

**Comment by jaynus** [comment]
Caused by this code:

https://github.com/amethyst/amethyst/blob/70f13782da68ad488a8628d202e00b31f65e7bca/amethyst_ui/src/glyphs.rs#L553-L556

**Comment by fhaynes** [comment]
Approved for 1.5 hours.

**Comment by Frizi** [comment]
After digging for a while, it turns out not only swizzle is a problem. `R8Srgb` format is not supported on macos (only on ios/tvos). Changing that to `R8Unorm` pushes the problem further. This time it turns out spirv-cross generated shader is not able to sample that texture correctly. Here is the error
```
validateFunctionArguments:3379: failed assertion `Fragment Function(main0): The pixel format (MTLPixelFormatR8Uint) of the texture (name:<null>) bound at index 0 is incompatible with the data type (MTLDataTypeFloat) of the texture parameter (_13 [[texture(0)]]). MTLPixelFormatR8Uint is compatible with the data type(s) (
    uint,
    ushort
).'
```

Seems like single channel unorm cannot be sampled as float, which would require changing the shader for glyph rendering. Unfortunately, that would also require frequent pipeline switches during UI rendering.

**Comment by fhaynes** [comment]
@omni-viral @termhn @jaynus any ideas on this?

**Comment by termhn** [comment]
Maybe we should just use 2 or more channel image and possibly pack new glyphs in different channels

**Comment by omni-viral** [comment]
@Frizi it should be `MTLPixelFormatR8Unorm`, not `MTLPixelFormatR8Uint`

**Comment by rayrrr** [comment]
Hey all, cool project! I am experiencing this same exact `Format R8Srgb is not supported...` error on my Mac trying to run the `pong_tutorial_05` example. I'm running Mojave 10.14.5 and know my way around `git`. If there is anything I can do to help please let me know!

**Comment by chrisburnor** [comment]
A temporary workaround for those who are blocked by the regression is the following patch to https://github.com/amethyst/amethyst/blob/70f13782da68ad488a8628d202e00b31f65e7bca/amethyst_ui/src/glyphs.rs#L553-L556

```
--- a/amethyst_ui/src/glyphs.rs
+++ b/amethyst_ui/src/glyphs.rs
@@ -17,7 +17,7 @@ use amethyst_rendy::{
         command::QueueId,
         factory::{Factory, ImageState},
         hal,
-        texture::{pixel::R8Srgb, TextureBuilder},
+        texture::{pixel::*, TextureBuilder},
     },
     resources::Tint,
     Backend, Texture,
@@ -550,10 +550,13 @@ fn create_glyph_texture<B: Backend>(
         .with_view_kind(hal::image::ViewKind::D2)
         .with_data_width(w)
         .with_data_height(h)
-        .with_data(vec![R8Srgb { repr: [0] }; (w * h) as _])
+        .with_data(vec![R8Unorm { repr: [0] }; (w * h) as _])
         // TODO: This will not work properly on metal :(
         // need to add extra uniform and mask in shader for metal
-        .with_swizzle(Swizzle(C::One, C::One, C::One, C::R))
+        .with_swizzle(Swizzle::NO)
         .build(
             ImageState {
```

This at least gives me my UI back, though the colors are off (white has turned into red) and I don't think this is a general solution.

**Comment by rayrrr** [comment]
Here's a full backtrace of this type of error:

```
thread '<unnamed>' panicked at 'Failed to create glyph texture: ErrorMessage { msg: "Format R8Srgb is not supported and no suitable conversion found." }

stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized::h0dd0ab15186ab80f (0x10f47e2ec)
   1: backtrace::backtrace::trace::ha86204ca5553ec51 (0x10f47e272)
   2: backtrace::capture::Backtrace::create::h25458936257242b9 (0x10f470216)
   3: backtrace::capture::Backtrace::new_unresolved::h86f693e1574d4a3d (0x10f470197)
   4: failure::backtrace::internal::InternalBacktrace::new::h45f8a345f85a1824 (0x10f388ccf)
   5: failure::backtrace::Backtrace::new::hef5fdb7e5f99a5e8 (0x10f389b6e)
   6: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from::h16b8872b0298a6d3 (0x10ed1e4bc)
   7: <failure::error::Error as core::convert::From<F>>::from::hf1714013f97d8ba4 (0x10ed1af97)
   8: failure::error_message::err_msg::hc406b0bb40ff92d7 (0x10ed1e2df)
   9: rendy_texture::texture::TextureBuilder::build::{{closure}}::hbba501826d051612 (0x10dc06e63)
  10: core::option::Option<T>::ok_or_else::h1e645ab2a78251b0 (0x10de3c9e3)
  11: rendy_texture::texture::TextureBuilder::build::h8fe5307bf4bcd986 (0x10dc053dc)
  12: amethyst_ui::glyphs::create_glyph_texture::h603cca1f11f3a8fc (0x10d92d1f5)
  13: <amethyst_ui::glyphs::UiGlyphsSystem<B> as shred::system::System>::run::{{closure}}::hccf64b2390691c2c (0x10d931376)
  14: core::option::Option<T>::get_or_insert_with::h1f842558c1a13660 (0x10de4b2d2)
  15: <amethyst_ui::glyphs::UiGlyphsSystem<B> as shred::system::System>::run::h6a123e959c17a071 (0x10d92e109)
  16: <T as shred::system::RunNow>::run_now::h45cf9aecf9756f6f (0x10d92d58b)
  17: shred::dispatch::stage::Stage::execute::{{closure}}::hd48930c2797f9b68 (0x10f554306)
  18: <rayon::iter::for_each::ForEachConsumer<F> as rayon::iter::plumbing::Folder<T>>::consume_iter::{{closure}}::h56b2c87e3dfb0070 (0x10f55145a)
  19: <core::slice::IterMut<T> as core::iter::traits::iterator::Iterator>::fold::h82d2f89aedeb8735 (0x10f556ae8)
  20: <rayon::iter::for_each::ForEachConsumer<F> as rayon::iter::plumbing::Folder<T>>::consume_iter::h13995b516cf66f97 (0x10f551421)
  21: rayon::iter::plumbing::Producer::fold_with::h219b98d1831bdbba (0x10f5484ad)
  22: rayon::iter::plumbing::bridge_producer_consumer::helper::h2458bd0a753e6e0a (0x10f552f76)
  23: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}::hdd519ae402dd4d17 (0x10f5531aa)
  24: rayon_core::join::join_context::{{closure}}::{{closure}}::h1749199734d655b5 (0x10f551f0d)
  25: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::{{closure}}::hf4115dc0c7a6517b (0x10f541e30)
  26: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hce1085b9591aec0e (0x10f5513d0)
  27: std::panicking::try::do_call::h4085ada4c1422c72 (0x10f53d494)
  28: ___rust_maybe_catch_panic (0x10f61614e)
  29: std::panicking::try::h51f879a2e6a9a595 (0x10f53d091)
  30: std::panic::catch_unwind::h82e89fed24986ef0 (0x10f552470)
  31: rayon_core::unwind::halt_unwinding::hb52bb2d27e55f66c (0x10f5522d8)
  32: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h4fde538d27a31ea4 (0x10f5417e8)
  33: rayon_core::job::JobRef::execute::he3de27e89675b048 (0x10f56e117)
  34: rayon_core::registry::WorkerThread::execute::hd8f6a27c9d4e8ba5 (0x10f55c7dc)
  35: rayon_core::registry::WorkerThread::wait_until_cold::h80c3ddd1aa314398 (0x10f55c51e)
  36: rayon_core::registry::WorkerThread::wait_until::h459ec0c25708408f (0x10f55bebf)
  37: rayon_core::registry::main_loop::he4120203683ff4f5 (0x10f55cf32)
  38: rayon_core::registry::Registry::new::{{closure}}::h16950a443ccccc64 (0x10f55b2ff)
  39: std::sys_common::backtrace::__rust_begin_short_backtrace::h23d31dcf17c40f72 (0x10f56005f)
  40: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::he72e65dd66dbde0b (0x10f57180f)
  41: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hbf70f2d7276b2d50 (0x10f570b0f)
  42: std::panicking::try::do_call::h92f0b14a1a4ef1de (0x10f571c6c)
  43: ___rust_maybe_catch_panic (0x10f61614e)
  44: std::panicking::try::h2ec2950ea823f68f (0x10f571934)
  45: std::panic::catch_unwind::hd60b0722ca5f69ee (0x10f570d8f)
  46: std::thread::Builder::spawn_unchecked::{{closure}}::h598195b9dc06e92a (0x10f57165d)
  47: core::ops::function::FnOnce::call_once{{vtable.shim}}::hb83220feb3963507 (0x10f560384)
  48: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hf8766009c029bc09 (0x10f6043dd)
  49: std::sys::unix::thread::Thread::new::thread_start::hfdef4649a42cf26c (0x10f6156bd)
  50: __pthread_body (0x7fff78d7b2ea)
  51: __pthread_start (0x7fff78d7e248)', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:308
   7: <T as core::any::Any>::type_id
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/macros.rs:18
   9: core::result::Result<T,E>::expect
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/result.rs:825
  10: amethyst_ui::glyphs::create_glyph_texture
             at ./amethyst_ui/src/glyphs.rs:548
  11: <amethyst_ui::glyphs::UiGlyphsSystem<B> as shred::system::System>::run::{{closure}}
             at ./amethyst_ui/src/glyphs.rs:154
  12: core::option::Option<T>::get_or_insert_with
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/option.rs:814
  13: <amethyst_ui::glyphs::UiGlyphsSystem<B> as shred::system::System>::run
             at ./amethyst_ui/src/glyphs.rs:152
  14: <T as shred::system::RunNow>::run_now
             at /Users/rriga/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.7.2/src/system.rs:133
  15: shred::dispatch::stage::Stage::execute::{{closure}}
             at /Users/rriga/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.7.2/src/dispatch/stage.rs:104
  16: core::ptr::swap_nonoverlapping_bytes
             at /Users/rriga/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/for_each.rs:49
  17: <shred::dispatch::stage::StagesBuilder as core::default::Default>::default
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/slice/mod.rs:3150
  18: core::ptr::swap_nonoverlapping_bytes
             at /Users/rriga/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/for_each.rs:49
  19: <fxhash::FxHasher as core::default::Default>::default
             at /Users/rriga/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:108
  20: rayon::iter::plumbing::LengthSplitter::try
             at /Users/rriga/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:418
  21: rayon::iter::plumbing::LengthSplitter::try
             at /Users/rriga/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:413
  22: <alloc::collections::CollectionAllocErr as core::convert::From<core::alloc::LayoutErr>>::from
             at /Users/rriga/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:122
  23: <rayon_core::job::JobRef as core::cmp::PartialEq>::eq
             at /Users/rriga/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/job.rs:113
  24: core::ptr::swap_nonoverlapping_bytes
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panic.rs:309
  25: core::alloc::Layout::repeat
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panicking.rs:293
  26: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:87
  27: core::alloc::Layout::repeat
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panicking.rs:272
  28: rayon_core::latch::SpinLatch::new
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panic.rs:388
  29: rayon_core::latch::SpinLatch::new
             at /Users/rriga/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/unwind.rs:18
  30: <rayon_core::job::JobRef as core::cmp::PartialEq>::eq
             at /Users/rriga/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/job.rs:113
  31: rayon_core::job::JobRef::execute
             at /Users/rriga/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/job.rs:60
  32: rayon_core::registry::WorkerThread::wait_until_cold::{{closure}}
             at /Users/rriga/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/registry.rs:584
  33: rayon_core::registry::WorkerThread::take_local_job
             at /Users/rriga/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/registry.rs:568
  34: rayon_core::registry::WorkerThread::take_local_job
             at /Users/rriga/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/registry.rs:544
  35: rayon_core::registry::main_loop
             at /Users/rriga/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/registry.rs:666
  36: rayon_core::registry::Registry::new::{{closure}}
             at /Users/rriga/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/registry.rs:135
  37: crossbeam_epoch::guard::unprotected
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/sys_common/backtrace.rs:136
  38: std::sys::unix::condvar::Condvar::wait
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/thread/mod.rs:470
  39: <alloc::vec::SetLenOnDrop as core::ops::drop::Drop>::drop
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panic.rs:309
  40: std::thread::panicking
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panicking.rs:293
  41: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:87
  42: std::thread::panicking
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panicking.rs:272
  43: std::sys::unix::condvar::Condvar::wait
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panic.rs:388
  44: std::sys::unix::condvar::Condvar::wait
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/thread/mod.rs:469
  45: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/ops/function.rs:231
  46: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/liballoc/boxed.rs:702
  47: std::sys::unix::thread::Thread::new::thread_start
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/liballoc/boxed.rs:702
             at src/libstd/sys_common/thread.rs:14
             at src/libstd/sys/unix/thread.rs:80
  48: _pthread_body
  49: _pthread_start
```

**Comment by omni-viral** [comment]
@chrisburnor color is broken because you turned off swizzle. And sampling gives you in red channel what supposed to be in alpha channel.

**Comment by chrisburnor** [comment]
That's what I suspected @omni-viral. I was trying to find a swizzle that was compatible with `R8Unorm` but my purpose was mostly to unblock myself and others who were affected by this. 

Regarding a longer term solution, if these values are dependent on the hardware backend, should the swizzle and data vector be derived from attributes of that struct?

**Comment by omni-viral** [comment]
@chrisburnor exactly same swizzle that was there before for `R8Srgb`.

**Comment by Frizi** [comment]
The problem is that Metal API has no concept of swizzles. Hal emulates that to an extent that's supported without modifying shaders, i.e. there are certain format + swizzle combinations that can be translated to distinct metal formats (they kinda combine those concepts into one). Unfortunately, there is no "alpha channel + white" format, as far as i know the best you can hope for is "alpha + black". That means we do need to modify shaders to "offset" the values in the code, but only for text. Same shader is bound for rendering the rest of UI (the idea is to never switch pipelines).

And the above is what i tried to do. Unfortunately i was not able to even do that "alpha + black". As @omni-viral noted above, it seems that sampler type is choosen wrong. It doesn't respect that `Unorm` should be sampled as floats.

Changing channel layout as @termhn proposed is tricky, because the glyph library simply returns a single-channel buffer to splat onto texture at given place. Expanding that on CPU is obviously very costly. Maybe we would be able to do a blit in such a way to fill other channels with white, but it would be a terrible waste of memory anyway.

**Comment by omni-viral** [comment]
Can we try to add branching that depend on uniform value? This way branch shounldn't cost too much.

**Comment by rayrrr** [comment]
I have two semi-stupid questions about this as a long time Mac user.

1) Does the lack of Metal support only affect game developers, or also end users? In other words, if I develop and compile my game on Linux or Windows, will the compiled binary execute without issue on Mac, or have the same issues?

2) What the heck is a "swizzle"? My search engine research was not productive.

**Comment by omni-viral** [comment]
@rayrrr This problem will manifest itself is engine run over metal graphics backend. No matter how you compile it.
I think Wikipedia will explain it better than me [wwizzle](https://en.wikipedia.org/wiki/Swizzling_(computer_graphics))

**Comment by jojolepro** [comment]
@rayrrr you have to compile on mac to have a mac binary. The only exception is if you cross compile, but I don't suggest doing that as you would not be testing your game at the same time.

**Comment by Frizi** [comment]
I don't know how i did that, but now `R8Unorm` works. I think i have actually used `R8Uint` previously by mistake. Fix incoming! :)
