### ISSUE TITLE
[BUG] Panic on Windows when using sdl_controller in pong example

### ISSUE THREAD

**Issue by OskarPersson** [amethyst/amethyst#1779]
## Description

Panic when running pong example with `sdl_controller` feature on Windows

## Reproduction Steps

`cargo run --example pong --features "vulkan sdl_controller"`

## What You Expected to Happen

The program launches

## What Actually Happened

A panic during startup

## Screenshots and Logs

```
$ cargo run --example pong --features "vulkan sdl_controller"
    Finished dev [unoptimized + debuginfo] target(s) in 2.01s
     Running `target\debug\examples\pong.exe`
[INFO][winit::platform::platform::window] Guessed window DPI factor: 1.5
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: -2147417850, kind: Other, message: "Cannot change thread mode after it is set." }', src\libcore\result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: process didn't exit successfully: `target\debug\examples\pong.exe` (exit code: 101)
```

## Your Environment

1. Operating System - Windows 10 Pro
2. Operating System Version - 1803
3. Version of Amethyst - `ea083c38e9247e1e605dd68a69de4533ae9e9e3b`

**Comment by torkleyy** [comment]
Thanks for the report! Can you please post the full backtrace using `RUST_BACKTRACE=short cargo run --example pong --features "vulkan sdl_controller"`?

**Comment by OskarPersson** [comment]
```
[INFO][winit::platform::platform::window] Guessed window DPI factor: 1
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: -2147417850, kind: Other, message: "Cannot change thread mode after it is set." }', src\libcore\result.rs:997:5
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\sys\windows\backtrace\mod.rs:95
   1: std::sys::windows::backtrace::unwind_backtrace
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\sys\windows\backtrace\mod.rs:82
   2: std::sys_common::backtrace::_print
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\sys_common\backtrace.rs:71
   3: std::sys_common::backtrace::print
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\sys_common\backtrace.rs:59
   4: std::panicking::default_hook::{{closure}}
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:197
   5: std::panicking::default_hook
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:211
   6: std::panicking::rust_panic_with_hook
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:474
   7: std::panicking::continue_panic_fmt
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:381
   8: std::panicking::rust_begin_panic
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:308
   9: core::panicking::panic_fmt
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libcore\panicking.rs:85
  10: core::result::unwrap_failed<std::io::error::Error>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libcore\macros.rs:18
  11: core::result::Result<(), std::io::error::Error>::unwrap<(),std::io::error::Error>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libcore\result.rs:798
  12: cpal::cpal_impl::com::COM_INITIALIZED::__init
             at C:\Users\oskar\.cargo\registry\src\github.com-1ecc6299db9ec823\cpal-0.8.2\src\wasapi\com.rs:13
  13: std::thread::local::LocalKey<cpal::cpal_impl::com::ComInitialized>::init<cpal::cpal_impl::com::ComInitialized>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libstd\thread\local.rs:252
  14: std::thread::local::LocalKey<cpal::cpal_impl::com::ComInitialized>::try_with<cpal::cpal_impl::com::ComInitialized,closure,()>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libstd\thread\local.rs:301
  15: std::thread::local::LocalKey<cpal::cpal_impl::com::ComInitialized>::with<cpal::cpal_impl::com::ComInitialized,closure,()>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libstd\thread\local.rs:245
  16: cpal::cpal_impl::com::com_initialized
             at C:\Users\oskar\.cargo\registry\src\github.com-1ecc6299db9ec823\cpal-0.8.2\src\wasapi\com.rs:34
  17: core::ops::function::FnOnce::call_once<fn() -> cpal::cpal_impl::device::Enumerator,()>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libcore\ops\function.rs:231
  18: spin::once::Once<cpal::cpal_impl::device::Enumerator>::call_once<cpal::cpal_impl::device::Enumerator,fn() -> cpal::cpal_impl::device::Enumerator>
             at C:\Users\oskar\.cargo\registry\src\github.com-1ecc6299db9ec823\spin-0.5.0\src\once.rs:110
  19: lazy_static::lazy::Lazy<cpal::cpal_impl::device::Enumerator>::get
             at C:\Users\oskar\.cargo\registry\src\github.com-1ecc6299db9ec823\lazy_static-1.3.0\src\core_lazy.rs:21
  20: cpal::cpal_impl::device::{{impl}}::deref::__stability
             at <::lazy_static::__lazy_static_internal macros>:12
  21: cpal::cpal_impl::device::{{impl}}::deref
             at <::lazy_static::__lazy_static_internal macros>:13
  22: cpal::cpal_impl::device::default_device
             at C:\Users\oskar\.cargo\registry\src\github.com-1ecc6299db9ec823\cpal-0.8.2\src\wasapi\device.rs:712
  23: cpal::cpal_impl::device::default_output_device
             at C:\Users\oskar\.cargo\registry\src\github.com-1ecc6299db9ec823\cpal-0.8.2\src\wasapi\device.rs:726
  24: cpal::default_output_device
             at C:\Users\oskar\.cargo\registry\src\github.com-1ecc6299db9ec823\cpal-0.8.2\src\lib.rs:359
  25: amethyst_audio::output::{{impl}}::default
             at .\amethyst_audio\src\output.rs:32
  26: amethyst_audio::bundle::{{impl}}::default
             at .\amethyst_audio\src\bundle.rs:17
  27: pong::main
             at .\examples\pong\main.rs:78
  28: std::rt::lang_start::{{closure}}<core::result::Result<(), amethyst_error::Error>>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libstd\rt.rs:64
  29: std::rt::lang_start_internal::{{closure}}
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\rt.rs:49
  30: std::panicking::try::do_call<closure,i32>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:293
  31: panic_unwind::__rust_maybe_catch_panic
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libpanic_unwind\lib.rs:87
  32: std::panicking::try
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:272
  33: std::panic::catch_unwind
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panic.rs:388
  34: std::rt::lang_start_internal
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\rt.rs:48
  35: std::rt::lang_start<core::result::Result<(), amethyst_error::Error>>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libstd\rt.rs:64
  36: main
  37: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  38: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
  39: BaseThreadInitThunk
  40: RtlUserThreadStart
error: process didn't exit successfully: `target\debug\examples\pong.exe` (exit code: 101)
```

**Comment by torkleyy** [comment]
Thanks! Hmm, this doesn't look like an issue with `sdl_controller` though, more like an issue with `cpal` (audio).

**Comment by OskarPersson** [comment]
I will double check later but I'm pretty sure it only crashed when I enabled the `sdl_controller` feature.

**Comment by OskarPersson** [comment]
I've now verified that running `cargo run --example pong --features "vulkan"` on the same machine works as it should

**Comment by torkleyy** [comment]
Thanks! It seems like this is an issue when using cpal and SDL2 in combination. Both set the COM threading model, which isn't allowed.

Also see https://github.com/tomaka/cpal/blob/0f393f48a53ec012c449c88ffb6953f6006062cc/src/host/wasapi/com.rs#L11

**Comment by torkleyy** [comment]
https://github.com/emscripten-ports/SDL2/blob/33245ddcaf7caa032f187a2a72b919ce13010704/src/core/windows/SDL_windows.c#L66

So we need to initialize cpal before SDL2.

**Comment by Noah2610** [comment]
Just leaving my simple workaround solution here:

Simply initializing amethyst's `AudioBundle` before the `InputBundle` did the trick for me.
(Using amethyst v0.10.0, with newer versions the `DjSystem` doesn't seem to be initialized by the `AudioBundle` anymore.)
More precisely, the important part is probably initializing the `DjSystem` before the `InputSystem`.

Here is a commit from my game that fixed the issue for me:
https://github.com/Noah2610/LD44/commit/c57a34f1f815570be76bb8a703c977a56bbabe8c
