### ISSUE TITLE
Examples fail on FreeBSD: Failed to detect any valid GPUs in the current config, etc

### ISSUE THREAD

**Issue by yurivict** [amethyst/amethyst#1875]
I tried with every supported "features" value and all of them failed.
Should it be able to just use OpenGL?

```
$ cargo run --example sphere --features "vulkan"
    Finished dev [unoptimized + debuginfo] target(s) in 0.36s
     Running `target/debug/examples/sphere`
[INFO][amethyst::app] Initializing Amethyst...
[INFO][amethyst::app] Version: 0.12.0
[INFO][amethyst::app] Platform: x86_64-unknown-freebsd
[INFO][amethyst::app] Amethyst git commit: 0c5c6d8b71f9588375f3fa34b03894d2a4aec19a
[INFO][amethyst::app] Rustc version: 1.36.0 Stable
[INFO][winit::platform::platform::x11::window] Guessed window DPI factor: 1
[WARN][gfx_backend_vulkan] Unable to find layer: VK_LAYER_LUNARG_standard_validation
[WARN][rendy_factory::factory] Slow safety checks are enabled! Disable them in production by enabling the 'no-slow-safety-checks' feature!
[ERROR][gfx_backend_vulkan] 
GENERAL [Loader Message (0)] : setupLoaderTermPhysDevs:  Failed to detect any valid GPUs in the current config
object info: (type: INSTANCE, hndl: 34451264128)

[ERROR][gfx_backend_vulkan] 
GENERAL [Loader Message (0)] : setupLoaderTrampPhysDevs:  Failed during dispatch call of 'vkEnumeratePhysicalDevices' to lower layers or loader to get count.
object info: (type: INSTANCE, hndl: 34451264128)

[ERROR][gfx_backend_vulkan] 
GENERAL [Loader Message (0)] : setupLoaderTermPhysDevs:  Failed to detect any valid GPUs in the current config
object info: (type: INSTANCE, hndl: 34451264128)

[ERROR][gfx_backend_vulkan] 
GENERAL [Loader Message (0)] : setupLoaderTrampPhysDevs:  Failed during dispatch call of 'vkEnumeratePhysicalDevices' to lower layers or loader to get count.
object info: (type: INSTANCE, hndl: 34451264128)

thread 'main' panicked at 'Unable to enumerate adapters: ERROR_INITIALIZATION_FAILED', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

```
$ cargo run --example sphere --features "metal"
   Compiling gfx-backend-metal v0.2.4
   Compiling objc_exception v0.1.1
error: failed to run custom build command for `gfx-backend-metal v0.2.4`

Caused by:
  process didn't exit successfully: `/usr/home/yuri/rust-learn/amethyst/target/debug/build/gfx-backend-metal-392e4ce856ff3b73/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'unsupported target x86_64-unknown-freebsd', /home/yuri/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-metal-0.2.4/build.rs:17:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `objc_exception v0.1.1`

Caused by:
  process didn't exit successfully: `/usr/home/yuri/rust-learn/amethyst/target/debug/build/objc_exception-0acd53b28fa16779/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-freebsd")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-freebsd")
HOST = Some("x86_64-unknown-freebsd")
TARGET = Some("x86_64-unknown-freebsd")
TARGET = Some("x86_64-unknown-freebsd")
HOST = Some("x86_64-unknown-freebsd")
CC_x86_64-unknown-freebsd = None
CC_x86_64_unknown_freebsd = None
HOST_CC = None
CC = None
HOST = Some("x86_64-unknown-freebsd")
TARGET = Some("x86_64-unknown-freebsd")
HOST = Some("x86_64-unknown-freebsd")
CFLAGS_x86_64-unknown-freebsd = None
CFLAGS_x86_64_unknown_freebsd = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-Wall" "-Wextra" "-o" "/usr/home/yuri/rust-learn/amethyst/target/debug/build/objc_exception-4d28c8696df9e004/out/extern/exception.o" "-c" "extern/exception.m"
cargo:warning=extern/exception.m:1:10: fatal error: 'objc/objc.h' file not found
cargo:warning=#include <objc/objc.h>
cargo:warning=         ^~~~~~~~~~~~~
cargo:warning=1 error generated.
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-Wall" "-Wextra" "-o" "/usr/home/yuri/rust-learn/amethyst/target/debug/build/objc_exception-4d28c8696df9e004/out/extern/exception.o" "-c" "extern/exception.m" with args "cc" did not execute successfully (status code exit code: 1).

', /home/yuri/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.55/src/lib.rs:1672:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

```
$ cargo run --example sphere --features "empty"
    Finished dev [unoptimized + debuginfo] target(s) in 0.37s
     Running `target/debug/examples/sphere`
[INFO][amethyst::app] Initializing Amethyst...
[INFO][amethyst::app] Version: 0.12.0
[INFO][amethyst::app] Platform: x86_64-unknown-freebsd
[INFO][amethyst::app] Amethyst git commit: 0c5c6d8b71f9588375f3fa34b03894d2a4aec19a
[INFO][amethyst::app] Rustc version: 1.36.0 Stable
[INFO][winit::platform::platform::x11::window] Guessed window DPI factor: 1
[WARN][rendy_factory::factory] Slow safety checks are enabled! Disable them in production by enabling the 'no-slow-safety-checks' feature!
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorMessage { msg: "No physical devices found" }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I use nvidia-driver-390.87. OpenGL works.

**Comment by KuSpa** [comment]
Same. I did `amethyst new <game>` and changed little to nothing in the code. When executing `cargo run`, I get the following error:

<details><summary>Error Message</summary>

``` 
~/D/P/PlatformParty$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/platform_party`
[INFO][winit::platform::platform::x11::window] Guessed window DPI factor: 1
[INFO][amethyst::app] Initializing Amethyst...
[INFO][amethyst::app] Version: 0.12.0
[INFO][amethyst::app] Platform: x86_64-unknown-linux-gnu
[INFO][amethyst::app] Amethyst git commit: 
[INFO][amethyst::app] Rustc version: 1.36.0 Stable
[INFO][amethyst::app] Rustc git commit: a53f9df32fbb0b5f4382caaad8f1a46f36ea887c
[WARN][gfx_backend_vulkan] Unable to find extension: VK_KHR_wayland_surface
[WARN][gfx_backend_vulkan] Unable to find layer: VK_LAYER_LUNARG_standard_validation
[WARN][rendy_factory::factory] Slow safety checks are enabled! Disable them in production by enabling the 'no-slow-safety-checks' feature!
[ERROR][gfx_backend_vulkan] 
GENERAL [Loader Message (0)] : setupLoaderTermPhysDevs:  Failed to detect any valid GPUs in the current config
object info: (type: INSTANCE, hndl: 94167664261904)

[ERROR][gfx_backend_vulkan] 
GENERAL [Loader Message (0)] : setupLoaderTrampPhysDevs:  Failed during dispatch call of 'vkEnumeratePhysicalDevices' to lower layers or loader to get count.
object info: (type: INSTANCE, hndl: 94167664261904)

[ERROR][gfx_backend_vulkan] 
GENERAL [Loader Message (0)] : setupLoaderTermPhysDevs:  Failed to detect any valid GPUs in the current config
object info: (type: INSTANCE, hndl: 94167664261904)

[ERROR][gfx_backend_vulkan] 
GENERAL [Loader Message (0)] : setupLoaderTrampPhysDevs:  Failed during dispatch call of 'vkEnumeratePhysicalDevices' to lower layers or loader to get count.
object info: (type: INSTANCE, hndl: 94167664261904)

thread 'main' panicked at 'Unable to enumerate adapters: ERROR_INITIALIZATION_FAILED', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

</details>

### OS
Ubuntu 18.04.3 LTS

### GPU
Palit gtx 980ti

### Driver 
nvidia-driver-390

### Cargo.toml
``` 
[dependencies.amethyst]
version = "0.12.0"
features = ["vulkan"]
```

**Comment by jojolepro** [comment]
cc @amethyst/rendering

**Comment by KuSpa** [comment]
I don't know if its helps for @yurivict s problem, but after `sudo apt install nvidia-settings vulkan-utils
`, rebooting and creating a new project I could solve my problem.
