### ISSUE TITLE
[BUG] Pong Example Panicing When Adding TransformBundle

### ISSUE THREAD

**Issue by DeanBDean** [amethyst/amethyst#2110]
## Description

I have been going through the pong tutorial in the Amethyst book, and got to [this step](https://book.amethyst.rs/stable/pong-tutorial/pong-tutorial-03.html#capturing-user-input). When I attempt to run this code, the compile appears to work but then I get a runtime panic with the following message:

'Cannot insert multiple systems with the same name ("parent_hierarchy_system")'

If I remove the line `.with_bundle(TransformBundle::new())?` from the main function in main.rs, then the code compiles and runs, but I suspect as I continue the tutorial doing this will cause other errors.

## Reproduction Steps

1. Follow the amethyst book tutorial until the 3rd chapter, at the end of capturing-user-input
2. Run `cargo run`

## What You Expected to Happen

I hoped that the code would not panic, and that I could see logs of the captured inputs in the terminal.

## What Actually Happened

The code panicked with the error message

'Cannot insert multiple systems with the same name ("parent_hierarchy_system")'

## Screenshots and Logs

```
thread 'main' panicked at 'Cannot insert multiple systems with the same name ("parent_hierarchy_system")', /Users/<DeanBDean>/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.9.4/src/dispatch/builder.rs:172:17
stack backtrace:
   0:        0x10a243025 - std::sys_common::at_exit_imp::push::hbcb9accb9aed3616
   1:        0x10a263760 - core::fmt::ArgumentV1::show_usize::h5612effbabb12159
   2:        0x10a24046b - std::io::Write::write_fmt::h7bd7b6fe8b47c5fb
   3:        0x10a244d9a - std::panicking::default_hook::{{closure}}::heee79636c241547c
   4:        0x10a244aa5 - std::panicking::default_hook::hfcbd07059d15441e
   5:        0x10a245467 - <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get::h2b8b0a58863fcf2c
   6:        0x10a244fdd - std::panicking::continue_panic_fmt::h0e74ab2b215a1401
   7:        0x10a27b87e - std::panicking::begin_panic_fmt::hc4b1bbb2a0641af7
                               at src/libstd/panicking.rs:335
   8:        0x10a0c8c5b - <core::any::TypeId as core::cmp::PartialEq>::eq::h5f1ec39727a3ed91
   9:        0x10a0cc0cd - hashbrown::raw::bitmask::BitMask::lowest_set_bit_nonzero::he5da062205fb470d
  10:        0x10925a77f - <amethyst_core::deferred_dispatcher_operation::AddBundle<B> as amethyst_core::deferred_dispatcher_operation::DispatcherOperation>::exec::h47475debb172cb45
                               at /Users/<DeanBDean>/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst_core-0.8.1/src/deferred_dispatcher_operation.rs:175
  11:        0x1096b4f34 - <amethyst::game_data::GameDataBuilder as amethyst::game_data::DataInit<amethyst::game_data::GameData>>::build::{{closure}}::hdd56527dc6340075
                               at /Users/<DeanBDean>/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.13.2/src/game_data.rs:473
  12:        0x1096b760b - core::iter::traits::iterator::Iterator::try_for_each::call::{{closure}}::hfc07d2d328d6c85b
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/iter/traits/iterator.rs:1733
  13:        0x1096b5145 - core::iter::traits::iterator::Iterator::try_fold::haabd4807ec7e1a72
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/iter/traits/iterator.rs:1694
  14:        0x1096b5045 - core::iter::traits::iterator::Iterator::try_for_each::hb016408acbbf8498
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/iter/traits/iterator.rs:1736
  15:        0x1096b4d20 - <amethyst::game_data::GameDataBuilder as amethyst::game_data::DataInit<amethyst::game_data::GameData>>::build::h2e173a64517e524d
                               at /Users/<DeanBDean>/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.13.2/src/game_data.rs:470
  16:        0x10919330e - amethyst::app::ApplicationBuilder<S,T,E,X>::build::h9c067ba02a9bc3d7
                               at /Users/<DeanBDean>/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.13.2/src/app.rs:894
  17:        0x109191369 - amethyst::app::CoreApplication<T,E,R>::new::h2e249376af2c6240
                               at /Users/<DeanBDean>/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.13.2/src/app.rs:201
  18:        0x109580bd2 - speedometer_two::main::h2d6f7a7dd7f6edf8
                               at src/main.rs:42
  19:        0x1096a4e92 - std::rt::lang_start::{{closure}}::hb942e7ec7483df1e
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  20:        0x10a244eb8 - std::panicking::try::do_call::ha1a4587e2a4eb439
  21:        0x10a247a5f - panic_unwind::dwarf::eh::read_encoded_pointer::h8a85bd7bb8b1ba5e
  22:        0x10a2458ce - std::panicking::update_count_then_panic::hdc433ed3a79fd4d2
  23:        0x1096a4e72 - std::rt::lang_start::h674f034a79cf48b3
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  24:        0x109580da2 - speedometer_two::main::h2d6f7a7dd7f6edf8
```

## Your Environment

1. MacOS
2. 10.14.6
3. 0.13

## Additional Context
My main.rs looks like this

```
use amethyst::{
    input::{InputBundle, StringBindings},
    prelude::*,
    renderer::{
        plugins::{RenderFlat2D, RenderToWindow},
        types::DefaultBackend,
        RenderingBundle,
    },
    utils::application_root_dir,
    core::transform::TransformBundle,
};

mod pong;
mod systems;

use crate::pong::Pong;

fn main() -> amethyst::Result<()> {
    amethyst::start_logger(Default::default());
    let app_root = application_root_dir()?;
    let display_config_path = app_root.join("config").join("display.ron");
    let game_data = GameDataBuilder::default();
    let assets_dir = app_root.join("assets");
    let binding_path = app_root.join("config").join("bindings.ron");
    let input_bundle = InputBundle::<StringBindings>::new()
        .with_bindings_from_file(binding_path)?;

    let mut world = World::new();
    let game_data = GameDataBuilder::default()
        .with_bundle(TransformBundle::new())?
        .with_bundle(input_bundle)?
        .with(systems::PaddleSystem, "paddle_system", &["input_system"])
        .with_bundle(
            RenderingBundle::<DefaultBackend>::new()
                .with_plugin(
                    RenderToWindow::from_config_path(display_config_path)
                        .with_clear([0.0, 0.0, 0.0, 1.0])
                    )
                .with_plugin(RenderFlat2D::default())
            )?
        .with_bundle(TransformBundle::new())?;
    let mut game = Application::new(assets_dir, Pong, game_data)?;
    game.run();

    Ok(())
}
```

**Comment by DeanBDean** [comment]
In addition, [this person](https://stackoverflow.com/questions/59008310/amethyst-rust-cannot-insert-multiple-systems-with-the-same-name-parent-hiera) appears to have the same issue I do, expect that they are on Linux

**Comment by DeanBDean** [comment]
Nevermind, I literally added TransformBundle twice 🤦‍♂ . Closing
