### ISSUE TITLE
WASM: Flakey Issues

### ISSUE THREAD

**Issue by azriel91** [amethyst/amethyst#2228]
Flakey issues that are difficult to reproduce and hence diagnose.

These were taken from developer tools in Chrome 80.0.3987.163 on Windows 10.

<details>

<summary>Uncaught TypeError: Failed to execute 'decode' on 'TextDecoder': The encoded data was not valid.</summary>

```js
Uncaught TypeError: Failed to execute 'decode' on 'TextDecoder': The encoded data was not valid.
    at getStringFromWasm0 (pong_wasm.js:51)
    at imports.wbg.__wbg_error_4bb6c2a97407129a (pong_wasm.js:437)
    at console_error_panic_hook::hook::hd81200035512c8dc (:8000/wasm-function[1615]:0x225e8f)
    at core::ops::function::Fn::call::h34e5502b0fa74be7 (:8000/wasm-function[7756]:0x34a41a)
    at std::panicking::rust_panic_with_hook::h51683ee5b7e63e9b (:8000/wasm-function[1903]:0x24e71d)
    at rust_begin_unwind (:8000/wasm-function[5946]:0x33df7f)
    at core::panicking::panic_fmt::h2b80e721df69bc1e (:8000/wasm-function[6222]:0x341812)
    at core::str::slice_error_fail::h3df6552881c70828 (:8000/wasm-function[953]:0x19fae7)
    at core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::Range<usize>>::index::{{closure}}::hd78eb511dd019174 (:8000/wasm-function[6532]:0x344c35)
    at <str as core::fmt::Debug>::fmt::h794f0482dc328362 (:8000/wasm-function[844]:0x17e3c4)
```

</details>

<details>

<summary>Uncaught (in promise) RuntimeError: function signature mismatch</summary>

```js
Uncaught (in promise) RuntimeError: function signature mismatch
    at core::fmt::write::h0c8c4456865d5e80 (wasm-function[1259]:0x1e7b33)
    at core::fmt::Formatter::write_fmt::h2c4b4e990e590853 (wasm-function[5091]:0x32c486)
    at <wasm_bindgen::JsValue as core::fmt::Debug>::fmt::h59ac06cade4b203d (wasm-function[4526]:0x319958)
    at <&T as core::fmt::Debug>::fmt::ha0e15b4a61f62a38 (wasm-function[6938]:0x3477eb)
    at core::fmt::write::h0c8c4456865d5e80 (wasm-function[1259]:0x1e7b59)
    at <std::panicking::begin_panic_handler::PanicPayload as core::panic::BoxMeUp>::get::h09d60c7bc6665297 (wasm-function[3634]:0x2ec5a6)
    at std::panicking::rust_panic_with_hook::h51683ee5b7e63e9b (wasm-function[1903]:0x24e704)
    at rust_begin_unwind (wasm-function[5946]:0x33df7f)
    at core::panicking::panic_fmt::h2b80e721df69bc1e (wasm-function[6222]:0x341812)
    at core::result::unwrap_failed::hfb06c9d5998f46b1 (wasm-function[4829]:0x3249c2)
```

</details>

<details>

<summary>Uncaught (in promise) RuntimeError: unreachable</summary>

```js
Uncaught (in promise) RuntimeError: unreachable
    at __rust_start_panic (wasm-function[8118]:0x34b213)
    at rust_panic (wasm-function[6449]:0x343f0f)
    at std::panicking::rust_panic_with_hook::h51683ee5b7e63e9b (wasm-function[1903]:0x24e7db)
    at rust_begin_unwind (wasm-function[5946]:0x33df7f)
    at core::panicking::panic_fmt::h2b80e721df69bc1e (wasm-function[6222]:0x341812)
    at core::result::unwrap_failed::hfb06c9d5998f46b1 (wasm-function[4829]:0x3249c2)
    at <amethyst_assets::source::http::HttpSource as amethyst_assets::source::Source>::load::h9979f10944776162 (wasm-function[479]:0xdb076)
    at amethyst_assets::source::Source::load_with_metadata::hebf491e00d7cb981 (wasm-function[4086]:0x3058a9)
    at amethyst_assets::asset::Format::import::hed6ef59d819f76d9 (wasm-function[1098]:0x1c5053)
    at <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h19282b712b7102ce (wasm-function[3472]:0x2e25e5)
```

</details>

<details>

<summary>Uncaught (in promise) RuntimeError: memory access out of bounds</summary>

```js
Uncaught (in promise) RuntimeError: memory access out of bounds
    at dlmalloc::dlmalloc::Dlmalloc::free::h76c3823543791605 (wasm-function[602]:0x11ef4e)
    at __rdl_dealloc (wasm-function[6703]:0x346288)
    at __rust_dealloc (wasm-function[7091]:0x348284)
    at <amethyst_assets::source::http::HttpSource as amethyst_assets::source::Source>::load::h9979f10944776162 (wasm-function[479]:0xdae2c)
    at amethyst_assets::source::Source::load_with_metadata::hebf491e00d7cb981 (wasm-function[4086]:0x3058a9)
    at amethyst_assets::asset::Format::import::hddc9c39cd224d1f0 (wasm-function[788]:0x16a9f2)
    at <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h0d46f9f038bd7ad8 (wasm-function[2219]:0x274d8c)
    at <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute::ha1f328c02c870125 (wasm-function[1632]:0x22868d)
    at rayon_core::registry::WorkerThread::wait_until_cold::hc89301bf3bc18d7a (wasm-function[1694]:0x23185d)
    at rayon_core::registry::ThreadBuilder::run::h16148ef8b3c616a2 (wasm-function[533]:0xfbcce)
```

</details>

<details>

<summary>Uncaught RuntimeError: memory access out of bounds</summary>

```js
Uncaught RuntimeError: memory access out of bounds
    at winit::platform_impl::platform::backend::timeout::AnimationFrameRequest::new::{{closure}}::h29df63739b894df1 (wasm-function[5747]:0x33afa1)
    at <dyn core::ops::function::FnMut<()>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hdc152010b002975f (wasm-function[6594]:0x34548d)
    at __wbg_adapter_56 (http://localhost:8000/pkg/pong_wasm.js:242:10)
    at real (http://localhost:8000/pkg/pong_wasm.js:200:20)
```

</details>

<details>

<summary>panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Cannot read property 'status' of undefined</summary>

```js
panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Cannot read property 'status' of undefined
TypeError: Cannot read property 'status' of undefined
    at imports.wbg.__wbg_status_c3e03a51f02cdd6d (http://localhost:8000/pkg/pong_wasm.js:1119:38)
    at web_sys::features::gen_XmlHttpRequest::XmlHttpRequest::status::hdd50ed857b4539f8 (wasm-function[5449]:0x335464)
    at <amethyst_assets::source::http::HttpSource as amethyst_assets::source::Source>::load::h9979f10944776162 (wasm-function[479]:0xdad2e)
    at amethyst_assets::source::Source::load_with_metadata::hebf491e00d7cb981 (wasm-function[4086]:0x3058a9)
    at amethyst_assets::asset::Format::import::hed6ef59d819f76d9 (wasm-function[1098]:0x1c5053)
    at <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h19282b712b7102ce (wasm-function[3472]:0x2e25e5)
    at <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute::h74217de870eb09fd (wasm-function[1437]:0x208de4)
    at rayon_core::registry::WorkerThread::wait_until_cold::hc89301bf3bc18d7a (wasm-function[1694]:0x23185d)
    at rayon_core::registry::ThreadBuilder::run::h16148ef8b3c616a2 (wasm-function[533]:0xfbcce)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hde27818b90a40c45 (wasm-function[4847]:0x32528d))', C:\Users\azrie\.cargo\git\checkouts\amethyst-fedb0a1032a075ce\32b8a07\amethyst_assets\src\source\http.rs:74:22

Stack:

Error
    at imports.wbg.__wbg_new_59cb74e423758ede (http://localhost:8000/pkg/pong_wasm.js:425:19)
    at console_error_panic_hook::hook::hd81200035512c8dc (wasm-function[1615]:0x225dab)
    at core::ops::function::Fn::call::h34e5502b0fa74be7 (wasm-function[7756]:0x34a41a)
    at std::panicking::rust_panic_with_hook::h51683ee5b7e63e9b (wasm-function[1903]:0x24e71d)
    at rust_begin_unwind (wasm-function[5946]:0x33df7f)
    at core::panicking::panic_fmt::h2b80e721df69bc1e (wasm-function[6222]:0x341812)
    at core::result::unwrap_failed::hfb06c9d5998f46b1 (wasm-function[4829]:0x3249c2)
    at <amethyst_assets::source::http::HttpSource as amethyst_assets::source::Source>::load::h9979f10944776162 (wasm-function[479]:0xdb076)
    at amethyst_assets::source::Source::load_with_metadata::hebf491e00d7cb981 (wasm-function[4086]:0x3058a9)
    at amethyst_assets::asset::Format::import::hed6ef59d819f76d9 (wasm-function[1098]:0x1c5053)
```

</details>

**Comment by azriel91** [comment]
Memory access out of bounds issues are likely https://github.com/rustwasm/wasm-bindgen/issues/1963. Should be a high value fix for everyone.

**Comment by azriel91** [comment]
Using JavaScript to load assets removes the `Uncaught (in promise) RuntimeError: memory access out of bounds` crash from `amethyst_asset`, but exposes a similar error from `lewton` (Vorbis / OGG decoder).

Disabling audio in `pong_wasm` after that just leaves chrome to crash with `STATUS_ACCESS_VIOLATION` with no information to go on.
