### ISSUE TITLE
UiLabelBuilder panics when trying to build a label

### ISSUE THREAD

**Issue by JoshLambda** [amethyst/amethyst#2357]
Building a label with `UiLabelBuilder` panics (whereas building a button with `UiButtonBuilder` does work).

```
impl SimpleState for Game {
    fn on_start(&mut self, data: StateData<'_, GameData<'_, '_>>) {
        let StateData { mut world, .. } = data;

        // Building a button works

        let (_, _button) =
            UiButtonBuilder::<(), u32>::new("Button".to_string()).build_from_world(world);

        // Building a label panics!

        let (_, _label) = UiLabelBuilder::<u32>::new("Label".to_string()).build_from_world(world);
```

I'm using branch: master.

The message is: `thread 'main' panicked at 'Tried to fetch resource of type `Widgets<UiLabel>`[^1] from the `World`, but the resource does not exist.` 

I'm new to Amethyst, maybe I am doing something wrong?
The builder fails when doing this: `UiLabelBuilderResources::<I>::fetch(&world)`
So it looks like the `UiLabelBuilderResources` isn't available at startup in world, while `UiButtonBuilderResources` is?

Backtrace:
  ```
thread 'main' panicked at 'Tried to fetch resource of type `Widgets<UiLabel>`[^1] from the `World`, but the resource does not exist.

You may ensure the resource exists through one of the following methods:

* Inserting it when the world is created: `world.insert(..)`.
* If the resource implements `Default`, include it in a system's `SystemData`, and ensure the system is registered in the dispatcher.
* If the resource does not implement `Default`, insert it in the world during `System::setup`.

[^1]: Full type name: `amethyst_ui::widgets::Widgets<amethyst_ui::label::UiLabel>`', /rustc/dbf8b6bf116c7bece2987ff4bd2792f008a6ee77/src/libstd/macros.rs:16:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
[...]

  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:373
  13: shred::world::World::fetch_mut::{{closure}}
             at /rustc/dbf8b6bf116c7bece2987ff4bd2792f008a6ee77/src/libstd/macros.rs:16
  14: core::option::Option<T>::unwrap_or_else
             at /rustc/dbf8b6bf116c7bece2987ff4bd2792f008a6ee77/src/libcore/option.rs:428
  15: shred::world::World::fetch_mut
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.10.2/src/world/mod.rs:481
  16: <shred::world::data::Write<T,F> as shred::system::SystemData>::fetch
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.10.2/src/world/data.rs:118
  17: <amethyst_ui::label::UiLabelBuilderResources<I> as shred::system::SystemData>::fetch
             at /home/user/.cargo/git/checkouts/amethyst-fedb0a1032a075ce/c52a21d/amethyst_ui/src/label.rs:27
  18: amethyst_ui::label::UiLabelBuilder<I>::build_from_world
             at /home/user/.cargo/git/checkouts/amethyst-fedb0a1032a075ce/c52a21d/amethyst_ui/src/label.rs:227
  19: <my_game::Game as amethyst::state::SimpleState>::on_start
             at src/main.rs:119
  20: <T as amethyst::state::State<amethyst::game_data::GameData,amethyst::state_event::StateEvent>>::on_start
             at /home/user/.cargo/git/checkouts/amethyst-fedb0a1032a075ce/c52a21d/src/state.rs:309
  21: amethyst::state::StateMachine<T,E>::start
             at /home/user/.cargo/git/checkouts/amethyst-fedb0a1032a075ce/c52a21d/src/state.rs:395

[...]
```

**Comment by MrTanoshii** [comment]
Add `world.insert(Widgets::<UiLabel, u32>::default());` before building your button.
A good place is in the `on_start` of your State

**Comment by JoshLambda** [comment]
Thank you much!
Any idea why this insert is needed for labels, but not for buttons?
It would mean that a `Widgets::<UiButton, u32>` already exist in world by default, but I couldn't confirm that.

**Comment by MrTanoshii** [comment]
To be completely honest, I also am not 100% sure why this is the way it is and if this is the way it was intended to be.

My guess so far is that `UiButton` was already added because Buttons have event handling systems attached which must have it inserted into world by default. There's no such requirement with `UiLabel`

Also interestingly `UiButton` is only registered with u32 and not String #2300

**Comment by JoshLambda** [comment]
The inconsistency between `Widgets` types at startup still seems like a relevant bug to me.

**Comment by CleanCut** [comment]
@JoshLambda If the inconsistency still exists after the legion port (#2343), then let's open a new issue for that specifically. 👍
