### ISSUE TITLE
[BUG] 2D Starter Crashes on Window Resize

### ISSUE THREAD

**Issue by spwilson2** [amethyst/amethyst#2420]
## Description

When the game window is resized by dragging the window corner, the game crashes.

## Screenshots and Logs

Run output from terminal:
```
$ RUST_BACKTRACE=full cargo run
   Compiling amethyst-starter-2d v0.2.0 (/windows/sean.wilson/projects/amethyst-starter-2d)
    Finished dev [unoptimized + debuginfo] target(s) in 19.74s
     Running `target/debug/amethyst-starter-2d`
[INFO][amethyst::app] Initializing Amethyst...
[INFO][amethyst::app] Version: 0.15.0
[INFO][amethyst::app] Platform: x86_64-unknown-linux-gnu
[INFO][amethyst::app] Amethyst git commit: UNKNOWN
[INFO][amethyst::app] Rustc version: 1.45.2 Stable
[INFO][amethyst::app] Rustc git commit: d3fb005a39e62501b8b0b356166e515ae24e2e54
[INFO][winit::platform::platform::x11::window] Guessed window DPI factor: 1
[WARN][gfx_backend_vulkan] Unable to find layer: VK_LAYER_LUNARG_standard_validation
[WARN][rendy_factory::factory] Slow safety checks are enabled! Disable them in production by enabling the 'no-slow-safety-checks' feature!
[INFO][rendy_util::wrap] Slow safety checks are enabled! You can disable them in production by enabling the 'no-slow-safety-checks' feature!
[INFO][amethyst_starter_2d::state] handling key event: (LShift, Pressed)
[INFO][amethyst_starter_2d::state] handling key event: (LShift, Released)
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Err(DeviceLost(DeviceLost))`,
 right: `Ok(true)`', /windows/sean.wilson/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/macros.rs:16:9
stack backtrace:
   0:     0x562f0714c1a5 - backtrace::backtrace::libunwind::trace::ha215bbf14e328799
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x562f0714c1a5 - backtrace::backtrace::trace_unsynchronized::h3384b099b135857a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x562f0714c1a5 - std::sys_common::backtrace::_print_fmt::hfec93740f7294682
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x562f0714c1a5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5fe20777f4174074
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x562f07173d3c - core::fmt::write::he14c3177144df275
                               at src/libcore/fmt/mod.rs:1076
   5:     0x562f07148e13 - std::io::Write::write_fmt::h8e26323bfab8bcc5
                               at src/libstd/io/mod.rs:1537
   6:     0x562f0714e9f0 - std::sys_common::backtrace::_print::h9cfa4c87526ba064
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x562f0714e9f0 - std::sys_common::backtrace::print::h94936584848b3272
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x562f0714e9f0 - std::panicking::default_hook::{{closure}}::h733b20cc9b496e46
                               at src/libstd/panicking.rs:198
   9:     0x562f0714e73c - std::panicking::default_hook::h556d8cff6c12a651
                               at src/libstd/panicking.rs:218
  10:     0x562f0714f027 - std::panicking::rust_panic_with_hook::ha0c7ca5b39baa9d5
                               at src/libstd/panicking.rs:486
  11:     0x562f0714ec2b - rust_begin_unwind
                               at src/libstd/panicking.rs:388
  12:     0x562f0714eb9b - std::panicking::begin_panic_fmt::ha757bc84d5ed8cb6
                               at src/libstd/panicking.rs:342
  13:     0x562f064a8b60 - rendy_frame::frame::Frames<B>::wait_complete::h5749bc45a6790ba6
                               at /windows/sean.wilson/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/macros.rs:16
  14:     0x562f063857ba - rendy_graph::graph::Graph<B,T>::run::h82d83af6441ec1a2
                               at /windows/sean.wilson/.cargo/registry/src/github.com-1ecc6299db9ec823/rendy-graph-0.4.1/src/graph/mod.rs:147
  15:     0x562f06402be9 - amethyst_rendy::system::RenderingSystem<B,G>::run_graph::hce7605649249cff0
                               at /windows/sean.wilson/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst_rendy-0.5.0/src/system.rs:126
  16:     0x562f06404316 - <amethyst_rendy::system::RenderingSystem<B,G> as shred::system::RunNow>::run_now::h1eda58ef0d81cec2
                               at /windows/sean.wilson/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst_rendy-0.5.0/src/system.rs:143
  17:     0x562f070644ac - shred::dispatch::dispatcher::Dispatcher::dispatch_thread_local::h96430d4aae56b312
                               at /windows/sean.wilson/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.10.2/src/dispatch/dispatcher.rs:113
  18:     0x562f0706422e - shred::dispatch::dispatcher::Dispatcher::dispatch::hf508d706144a8bd3
                               at /windows/sean.wilson/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.10.2/src/dispatch/dispatcher.rs:65
  19:     0x562f065e0580 - amethyst::game_data::GameData::update::h4988d528477da87e
                               at /windows/sean.wilson/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.15.0/src/game_data.rs:47
  20:     0x562f062bf1ba - <T as amethyst::state::State<amethyst::game_data::GameData,amethyst::state_event::StateEvent>>::update::h003f282bfedbabbe
                               at /windows/sean.wilson/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.15.0/src/state.rs:345
  21:     0x562f064e3043 - amethyst::state::StateMachine<T,E>::update::h0a0c6fed5a2805af
                               at /windows/sean.wilson/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.15.0/src/state.rs:447
  22:     0x562f062c6b3d - amethyst::app::CoreApplication<T,E,R>::advance_frame::h1fe4dbdd96df8579
                               at /windows/sean.wilson/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.15.0/src/app.rs:378
  23:     0x562f062c701f - amethyst::app::CoreApplication<T,E,R>::run::h083f4837068b70e8
                               at /windows/sean.wilson/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.15.0/src/app.rs:242
  24:     0x562f063024d9 - amethyst_starter_2d::main::h99ace7311dc4a008
                               at src/main.rs:34
  25:     0x562f0626845b - std::rt::lang_start::{{closure}}::h865a7556a6c502a6
                               at /windows/sean.wilson/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  26:     0x562f0714f4b8 - std::rt::lang_start_internal::{{closure}}::hefb489d56a389b75
                               at src/libstd/rt.rs:52
  27:     0x562f0714f4b8 - std::panicking::try::do_call::hb2bfa58b743656f1
                               at src/libstd/panicking.rs:297
  28:     0x562f0714f4b8 - std::panicking::try::haaa85a89ce3784c3
                               at src/libstd/panicking.rs:274
  29:     0x562f0714f4b8 - std::panic::catch_unwind::h49baa277f74e60cb
                               at src/libstd/panic.rs:394
  30:     0x562f0714f4b8 - std::rt::lang_start_internal::h7aa2f6739b31fe58
                               at src/libstd/rt.rs:51
  31:     0x562f06268437 - std::rt::lang_start::he88f34e5aabf6c41
                               at /windows/sean.wilson/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  32:     0x562f0630285a - main
  33:     0x7f6ba18b3002 - __libc_start_main
  34:     0x562f0617f34e - _start
  35:                0x0 - <unknown>
[ERROR][rendy_resource::escape] Terminal must be dropped after all `Escape`s
[ERROR][rendy_resource::escape] Terminal must be dropped after all `Escape`s
[ERROR][rendy_resource::escape] Terminal must be dropped after all `Escape`s
[ERROR][rendy_resource::escape] Terminal must be dropped after all `Escape`s
[ERROR][rendy_resource::escape] Terminal must be dropped after all `Escape`s
[ERROR][rendy_resource::escape] Terminal must be dropped after all `Escape`s
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(8192) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(524288) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(2048000) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(1024) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(4194304) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(65536) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(720896) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(2097152) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(4096) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(16384) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(256) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(32768) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(1048576) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(131072) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(2048) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(262144) is still used
[ERROR][rendy_descriptor::allocator] Not all descriptor sets were deallocated
[ERROR][rendy_descriptor::allocator] Descriptor pool is still in use during allocator disposal. DescriptorPool { size: 64, free: 52, freed: 6 }
[ERROR][rendy_descriptor::allocator] Not all descriptor sets were deallocated
[ERROR][rendy_descriptor::allocator] Descriptor pool is still in use during allocator disposal. DescriptorPool { size: 64, free: 62, freed: 1 }
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
```

## Your Environment

OS: Linux
```
$ cat /etc/lsb-release 
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=20.0.3
DISTRIB_CODENAME=Lysia
DISTRIB_DESCRIPTION="Manjaro Linux"
```
Window Manager: i3 (X11)
Version of Amethyst: 0.15.0
Version of 2D Starter: 60a10279ecfd4944f48e2d79fa2ed068cd70dfe4
https://github.com/amethyst/amethyst-starter-2d.git

```
$ cargo --version
cargo 1.45.1 (f242df6ed 2020-07-22)
$ rustc  --version
rustc 1.45.2 (d3fb005a3 2020-07-31)
```

**Comment by Blisto91** [comment]
Will see if I can reproduce later today.

**Comment by Blisto91** [comment]
Okay so i went with option C of disconnecting the broken keyboard and track pad from another laptop and used an external keyboard and track pad to install Linux.

I'm using Linux mint 20 with i3 and i have not been able to produce a crash yet.
I even tried using the exact same commit and forced the amethyst version to 0.15.0
Might be something related to your Linux distro which i can see is based on Arch Linux?

I'm gonna do some digging.
If i don't find anything i might try to install your distro.

**Comment by spwilson2** [comment]
@Blisto91, I'll try running in a VM and see if it occurs there. 

Also I didn't specify in the initial bug report but it looks like this only happens with i3 float windows. This could be relevant because i3 floats seem to cause (what I wager are) redraw events very rapidly. This might be key to triggering a race condition.

**Comment by Blisto91** [comment]
It's a dummy backend so you can still test code for compiler errors and such without being on a environment that supports all the graphics stuff it normally would.
Here's from the respective docs.rs.
```
Mock backend implementation to test the code for compile errors outside of the graphics development environment.
```
But since you asked I guess this info could be mentioned in a place that's more central to amethyst. Couldn't really answer before finding docs.rs for the backend myself 😁

I tried with the window in floating mode without luck. 
But I didn't think to try with empty backend so I'll try that next!

**Comment by LukasDoesDev** [comment]
I am getting the exact same behaviour, except the stack trace is for something about PointerState:
```
thread 'main' panicked at 'attempted to leave type `platform::platform::x11::util::input::PointerState` uninitialized, which is invalid', /home/luukas/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/x11/util/input.rs:94:51
stack backtrace:
   0:     0x55a7b61012ac - std::backtrace_rs::backtrace::libunwind::trace::hf6a6dfd7da937cb0
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55a7b61012ac - std::backtrace_rs::backtrace::trace_unsynchronized::hc596a19e4891f7f3
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55a7b61012ac - std::sys_common::backtrace::_print_fmt::hb16700db31584325
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55a7b61012ac - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h231c4190cfa75162
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55a7b6123e7c - core::fmt::write::h2a1462b5f8eea807
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/fmt/mod.rs:1163:17
   5:     0x55a7b60fd6c5 - std::io::Write::write_fmt::h71ddfebc68685972
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/io/mod.rs:1696:15
   6:     0x55a7b6102ed0 - std::sys_common::backtrace::_print::hcc197d4bebf2b369
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55a7b6102ed0 - std::sys_common::backtrace::print::h335a66af06738c7c
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55a7b6102ed0 - std::panicking::default_hook::{{closure}}::h6fac9ac9c8b79e52
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:210:50
   9:     0x55a7b6102a85 - std::panicking::default_hook::h341c1030c6a1161b
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:227:9
  10:     0x55a7b6103584 - std::panicking::rust_panic_with_hook::h50680ff4b44510c6
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:624:17
  11:     0x55a7b6103032 - std::panicking::begin_panic_handler::{{closure}}::h9371c0fbb1e8465a
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:519:13
  12:     0x55a7b6101754 - std::sys_common::backtrace::__rust_end_short_backtrace::h9b3efa22a5768c0f
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x55a7b6102fc9 - rust_begin_unwind
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
  14:     0x55a7b5231401 - core::panicking::panic_fmt::h23b9203e89cc61cf
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
  15:     0x55a7b523134d - core::panicking::panic::h0ba7146865b2f9d6
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:50:5
  16:     0x55a7b5a10470 - core::mem::uninitialized::h5694e46960c91ef3
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/mem/mod.rs:665:9
  17:     0x55a7b5a10470 - winit::platform::platform::x11::util::input::<impl winit::platform::platform::x11::xdisplay::XConnection>::query_pointer::h55c2433ffb81b84f
                               at /home/luukas/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/x11/util/input.rs:94:51
  18:     0x55a7b5852b1a - winit::platform::platform::x11::EventsLoop::process_event::h69bc0dad3d150018
                               at /home/luukas/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/x11/mod.rs:956:45
  19:     0x55a7b584e10f - winit::platform::platform::x11::EventsLoop::poll_events::hb5a9c4be869cee5b
                               at /home/luukas/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/x11/mod.rs:270:13
  20:     0x55a7b584d45a - winit::platform::platform::EventsLoop::poll_events::h0e35c26bf82508f9
                               at /home/luukas/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/mod.rs:522:44
  21:     0x55a7b5848bf4 - winit::EventsLoop::poll_events::h2bc4e1edd8f717af
                               at /home/luukas/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/lib.rs:277:9
  22:     0x55a7b584c119 - <amethyst_window::system::EventsLoopSystem as shred::system::RunNow>::run_now::ha4f700ff6029351c
                               at /home/luukas/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst_window-0.15.3/src/system.rs:116:9
  23:     0x55a7b6001db7 - shred::dispatch::dispatcher::Dispatcher::dispatch_thread_local::h213e57fd07dd88ad
                               at /home/luukas/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.10.2/src/dispatch/dispatcher.rs:113:13
  24:     0x55a7b6001b5e - shred::dispatch::dispatcher::Dispatcher::dispatch::h947b4f9595018578
                               at /home/luukas/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.10.2/src/dispatch/dispatcher.rs:65:9
  25:     0x55a7b560d448 - amethyst::game_data::GameData::update::hc12cf5e8bc402458
                               at /home/luukas/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.15.3/src/game_data.rs:47:13
  26:     0x55a7b54508cc - <T as amethyst::state::State<amethyst::game_data::GameData,amethyst::state_event::StateEvent>>::update::h89b841fd2b0f057e
                               at /home/luukas/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.15.3/src/state.rs:345:9
  27:     0x55a7b558193a - amethyst::state::StateMachine<T,E>::update::h9d834c1fd908a435
                               at /home/luukas/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.15.3/src/state.rs:447:21
  28:     0x55a7b5521237 - amethyst::app::CoreApplication<T,E,R>::advance_frame::hfc247de06288cfd7
                               at /home/luukas/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.15.3/src/app.rs:379:13
  29:     0x55a7b552153e - amethyst::app::CoreApplication<T,E,R>::run::hd3340fd4b30d3da7
                               at /home/luukas/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.15.3/src/app.rs:243:13
  30:     0x55a7b5383d97 - open_space_explorer_rs::main::ha8e997b3c033f57b
                               at /home/luukas/dev/open_space_explorer_rs/src/main.rs:34:5
  31:     0x55a7b52bad8b - core::ops::function::FnOnce::call_once::h924ba05a91ffb27f
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
  32:     0x55a7b545464e - std::sys_common::backtrace::__rust_begin_short_backtrace::he450b9d6bec424c2
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:123:18
  33:     0x55a7b52b13c1 - std::rt::lang_start::{{closure}}::h3a5bed6c20a96d2f
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/rt.rs:146:18
  34:     0x55a7b6100f8b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hc56adab7a77ec6e3
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:259:13
  35:     0x55a7b6100f8b - std::panicking::try::do_call::h29f013120c5abc65
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
  36:     0x55a7b6100f8b - std::panicking::try::h86d5b2b66caec4cf
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
  37:     0x55a7b6100f8b - std::panic::catch_unwind::h7dd136d787f51397
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
  38:     0x55a7b6100f8b - std::rt::lang_start_internal::{{closure}}::h4a199351e630a8a5
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/rt.rs:128:48
  39:     0x55a7b6100f8b - std::panicking::try::do_call::h20ceb9e5dff838c6
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
  40:     0x55a7b6100f8b - std::panicking::try::hc2abb46a5e41bd43
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
  41:     0x55a7b6100f8b - std::panic::catch_unwind::h52c3eb4408ad6dfb
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
  42:     0x55a7b6100f8b - std::rt::lang_start_internal::hd15a47be08101c28
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/rt.rs:128:20
  43:     0x55a7b52b1390 - std::rt::lang_start::h110282bb53fbf5db
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/rt.rs:145:17
  44:     0x55a7b5383ecc - main
  45:     0x7fa42f445b25 - __libc_start_main
  46:     0x55a7b5231c7e - _start
  47:                0x0 - <unknown>
  ```

**Comment by LukasDoesDev** [comment]
Seems like the GitHub issue for that is #2569, sorry for the trouble
