### ISSUE TITLE
gfx_backend_vulkan problems on arch linux

### ISSUE THREAD

**Issue by leeperprwn** [amethyst/amethyst#2686]
## Description
I'm trying to run a basic rendering example of amethyst on Arch Linux but I'm running into issues with amdvlk and gfx_backend_vulkan. These problems relate to finding the correct amdvlk.so file and detecting problems in this entire process.

I have installed both amdvlk64 and amdvlk32 on my Arch Linux system. The 64 bit version is found under /usr/lib/amdvlk64.so and the 32 bit version is found under /usr/lib32/amdvlk32.so.

When I run the basic example I get the following log output that describes how /usr/lib/amdvlk32.so can't be found (1).

Next I create a symlink for /usr/lib32/amdvlk32.so to /usr/lib/amdvlk32.so so that the 32 bit version can be found in /usr/lib.
I get the following log output where I've removed the beginning and the end as they are the same as in 1. (2)

Since it seems to be saying that it's the wrong ELF class on amdvlk32.so I then instead symlink amdvlk32.so to point at /usr/lib/amdvlk64.so
When I do that the above error before the panic goes away but the same panic happens and the logged errors after the panic stay the same.

## Reproduction Steps

1. Use Arch Linux
2. Install `lib32-amdvlk` and `amdvlk` with pacman
3. Create a new project from the github of amethyst and run the following code
```rust
use amethyst::{
    prelude::*,
    renderer::{
        plugins::{RenderFlat2D, RenderToWindow},
        types::DefaultBackend,
        RenderingBundle,
        rendy::hal::command::ClearColor
    },
    utils::application_root_dir,
    //winit::event::{Event, KeyboardInput, VirtualKeyCode, WindowEvent},
};

pub struct Pong;

impl SimpleState for Pong {
}

fn main() -> amethyst::Result<()> {
    amethyst::start_logger(Default::default());

    let app_root = application_root_dir()?;

    let display_config_path = app_root.join("config").join("display.ron");
    let mut game_data = DispatcherBuilder::default();
    game_data.add_bundle(
        RenderingBundle::<DefaultBackend>::new()
        // The RenderToWindow plugin provides all the scaffolding for opening a window and drawing on it
        .with_plugin(
            RenderToWindow::from_config_path(display_config_path)?
            .with_clear(ClearColor {
                float32: [0.0, 0.0, 0.0, 1.0],
            }))
        // RenderFlat2D plugin is used to render entities with a `SpriteRender` component.
        .with_plugin(RenderFlat2D::default()),
        );
    let assets_dir = app_root.join("assets");
    let game = Application::new(assets_dir, Pong, game_data)?;
    game.run();

    Ok(())
}
```
4. Go through the steps above by creating symlinks to the appropriate *.so files.

## What You Expected to Happen
I expect the vulkan not to error out.

## What Actually Happened
The graphics backend crashes

## Screenshots and Logs
(1)
```
[INFO][amethyst::app] Initializing Amethyst...
[INFO][amethyst::app] Version: 0.15.3
[INFO][amethyst::app] Platform: x86_64-unknown-linux-gnu
[INFO][amethyst::app] Amethyst git commit: f563103e169add05bdceb3e54e33270a330685db
[INFO][amethyst::app] Rustc version: 1.51.0 Stable
[INFO][amethyst::app] Rustc git commit: 2fd73fabe469357a12c2c974c140f67e7cdd76d0
[INFO][amethyst_assets::bundle] Adding importer for ext ron
[INFO][amethyst_assets::bundle] Adding importer for ext prefab
[INFO][amethyst_assets::bundle] Adding importer for ext bmp
[INFO][amethyst_assets::bundle] Adding importer for ext tga
[INFO][amethyst_assets::bundle] Adding importer for ext png
[INFO][amethyst_assets::bundle] Adding importer for ext jpg
[INFO][amethyst_assets::bundle] Adding importer for ext obj
[INFO][distill_daemon::daemon] Starting Daemon Loop
[INFO][distill_daemon::file_tracker::events] Scanned and compared 0 + 0, deleted 0
[ERROR][gfx_backend_vulkan] 
GENERAL [Loader Message (0)] : /usr/lib/amdvlk32.so: cannot open shared object file: No such file or directory
object info: (type: INSTANCE, hndl: 94886174677248)

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/user/development/project//src/amethyst/amethyst_
rendy/src/system.rs:239:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[ERROR][gfx_backend_vulkan] 
VALIDATION [VUID-vkFreeCommandBuffers-commandBufferCount-arraylength (257118683)] : Validation Error: [ VUID-vkFreeCommandBuffers-commandBufferCount-arraylength
 ] Object 0: handle = 0x564c69276320, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xf5351db | vkFreeCommandBuffers: parameter commandBufferCount must be greater
 than 0. The Vulkan spec states: commandBufferCount must be greater than 0 (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-v
kFreeCommandBuffers-commandBufferCount-arraylength)
object info: (type: DEVICE, hndl: 94886181692192)

[ERROR][gfx_backend_vulkan] 
VALIDATION [VUID-vkFreeCommandBuffers-commandBufferCount-arraylength (257118683)] : Validation Error: [ VUID-vkFreeCommandBuffers-commandBufferCount-arraylength
 ] Object 0: handle = 0x564c69276320, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xf5351db | vkFreeCommandBuffers: parameter commandBufferCount must be greater
 than 0. The Vulkan spec states: commandBufferCount must be greater than 0 (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-v
kFreeCommandBuffers-commandBufferCount-arraylength)
object info: (type: DEVICE, hndl: 94886181692192)
```
(2)
```
// ...
[ERROR][gfx_backend_vulkan] 
GENERAL [Loader Message (0)] : /usr/lib/amdvlk32.so: wrong ELF class: ELFCLASS32
object info: (type: INSTANCE, hndl: 93889813801216)

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/user/development/project/src/amethyst/amethyst_
rendy/src/system.rs:239:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
// ...
```

## Your Environment

Operating System: Arch Linux 
Operating System Version: 5.12.6-arch1-1
Version of Amethyst: github master branch commit c132d1a498350f6bd040d30dc0a061fc77b61f31

## Additional Context
I've looked around a bunch online for ways to solve this and one way I have tried to check if vulkan is working as it should is by installing and running `vulkinfo` as per the advice of the wiki.
`vulkinfo` does display information about my graphics card which seems to imply that it does work, but I don't know if it's checking the 32 or 64 bit version.
Additionally I can't uninstall the 32 bit version of `amdvlk`as it is a dependency for some other parts of my system. I don't see why it would be necessary to uninstall it but I haven't tried any solution that involves that.

**Comment by Epacnoss** [comment]
Which toolchain are you using?

**Comment by Kilso4dev** [comment]
I have the same problem using the main branch on the latest commit (6d0e7aa)
I also run Arch linux and when trying to compile the program specified above I get the following Error log:

```
[INFO][amethyst::app] Initializing Amethyst...
[INFO][amethyst::app] Version: 0.16.0
[INFO][amethyst::app] Platform: x86_64-unknown-linux-gnu
[INFO][amethyst::app] Amethyst git commit: 6d0e7aaf58a4d1483b902f63920044eabb865c92
[INFO][amethyst::app] Rustc version: 1.53.0 Stable
[INFO][amethyst::app] Rustc git commit: 53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/kilso/.cargo/git/checkouts/amethyst-fedb0a1032a075ce/6d0e7aa/amethyst_rendy/src/system.rs:240:51
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:50:5
   3: core::option::Option<T>::unwrap
             at /home/kilso/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:386:21
   4: amethyst_rendy::system::create_default_mat
             at /home/kilso/.cargo/git/checkouts/amethyst-fedb0a1032a075ce/6d0e7aa/amethyst_rendy/src/system.rs:240:18
   5: <amethyst_rendy::bundle::RenderingBundle<B> as amethyst_core::dispatcher::SystemBundle>::load
             at /home/kilso/.cargo/git/checkouts/amethyst-fedb0a1032a075ce/6d0e7aa/amethyst_rendy/src/bundle.rs:94:19
   6: amethyst_core::dispatcher::DispatcherBuilder::load
             at /home/kilso/.cargo/git/checkouts/amethyst-fedb0a1032a075ce/6d0e7aa/amethyst_core/src/dispatcher.rs:156:25
   7: amethyst_core::dispatcher::DispatcherBuilder::build
             at /home/kilso/.cargo/git/checkouts/amethyst-fedb0a1032a075ce/6d0e7aa/amethyst_core/src/dispatcher.rs:175:9
   8: <amethyst_core::dispatcher::DispatcherBuilder as amethyst::game_data::DataInit<amethyst::game_data::GameData>>::build
             at /home/kilso/.cargo/git/checkouts/amethyst-fedb0a1032a075ce/6d0e7aa/src/game_data.rs:64:26
   9: amethyst::app::ApplicationBuilder<S,T,E,X>::build
             at /home/kilso/.cargo/git/checkouts/amethyst-fedb0a1032a075ce/6d0e7aa/src/app.rs:820:20
  10: amethyst::app::CoreApplication<T,E,R>::new
             at /home/kilso/.cargo/git/checkouts/amethyst-fedb0a1032a075ce/6d0e7aa/src/app.rs:203:9
  11: amethyst_graphs::main
             at ./src/main.rs:37:16
  12: core::ops::function::FnOnce::call_once
             at /home/kilso/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[ERROR][gfx_backend_vulkan]
VALIDATION [VUID-vkFreeCommandBuffers-commandBufferCount-arraylength (257118683)] : Validation Error: [ VUID-vkFreeCommandBuffers-commandBufferCount-arraylength ] Object 0: handle = 0x556eca5f2698, typ
e = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xf5351db | vkFreeCommandBuffers: parameter commandBufferCount must be greater than 0. The Vulkan spec states: commandBufferCount must be greater than 0 (https:
//www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkFreeCommandBuffers-commandBufferCount-arraylength)
object info: (type: DEVICE, hndl: 93934329996952)

[ERROR][gfx_backend_vulkan]
VALIDATION [VUID-vkFreeCommandBuffers-commandBufferCount-arraylength (257118683)] : Validation Error: [ VUID-vkFreeCommandBuffers-commandBufferCount-arraylength ] Object 0: handle = 0x556eca5f2698, typ
e = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xf5351db | vkFreeCommandBuffers: parameter commandBufferCount must be greater than 0. The Vulkan spec states: commandBufferCount must be greater than 0 (https:
//www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkFreeCommandBuffers-commandBufferCount-arraylength)
object info: (type: DEVICE, hndl: 93934329996952)
```

It happened on both stable and nightly:
my stable build: `stable-x86_64-unknown-linux-gnu unchanged - rustc 1.53.0 (53cb7b09b 2021-06-17)`
my nightly build: `nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.56.0-nightly (2faabf579 2021-07-27)`
