### ISSUE TITLE
RenderingBundle has undocumented dependency when used with ApplicationBuilder

### ISSUE THREAD

**Issue by dragonrider7225** [amethyst/amethyst#2702]
## Description

`<RenderingBundle as SystemBundle>::load` calls `create_default_mat` with a set of resources that is doesn't include a `DefaultLoader`.

## Reproduction Steps
1. Create a `DispatcherBuilder`
2. Add a `RenderingBundle` with a reasonable set of `SystemBundle`s to the `DispatcherBuilder`
3. Create an `ApplicationBuilder`
4. Call `ApplicationBuilder::build` with the `DispatcherBuilder`

## What You Expected to Happen

I expected my program to not crash.

## What Actually Happened

My program crashed.

## Screenshots and Logs

The output from `$ RUST_BACKTRACE=1 cargo run` is as follows:
```
[INFO][amethyst::app] Initializing Amethyst...
[INFO][amethyst::app] Version: 0.16.0
[INFO][amethyst::app] Platform: x86_64-unknown-linux-gnu
[INFO][amethyst::app] Amethyst git commit: 6d0e7aaf58a4d1483b902f63920044eabb865c92
[INFO][amethyst::app] Rustc version: 1.53.0 Stable
[INFO][amethyst::app] Rustc git commit: 53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b
[DEBUG][amethyst_core::dispatcher] Building system
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ~/.cargo/git/checkouts/amethyst-fedb0a1032a075ce/6d0e7aa/amethyst_rendy/src/system.rs:240:51
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:50:5
   3: core::option::Option<T>::unwrap
             at ~/snap/rustup/common/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:386:21
   4: amethyst_rendy::system::create_default_mat
             at ~/.cargo/git/checkouts/amethyst-fedb0a1032a075ce/6d0e7aa/amethyst_rendy/src/system.rs:240:18
   5: <amethyst_rendy::bundle::RenderingBundle<B> as amethyst_core::dispatcher::SystemBundle>::load
             at ~/.cargo/git/checkouts/amethyst-fedb0a1032a075ce/6d0e7aa/amethyst_rendy/src/bundle.rs:94:19
   6: amethyst_core::dispatcher::DispatcherBuilder::load
             at ~/.cargo/git/checkouts/amethyst-fedb0a1032a075ce/6d0e7aa/amethyst_core/src/dispatcher.rs:156:25
   7: amethyst_core::dispatcher::DispatcherBuilder::build
             at ~/.cargo/git/checkouts/amethyst-fedb0a1032a075ce/6d0e7aa/amethyst_core/src/dispatcher.rs:175:9
   8: <amethyst_core::dispatcher::DispatcherBuilder as amethyst::game_data::DataInit<amethyst::game_data::GameData>>::build
             at ~/.cargo/git/checkouts/amethyst-fedb0a1032a075ce/6d0e7aa/src/game_data.rs:64:26
   9: amethyst::app::ApplicationBuilder<S,T,E,X>::build
             at ~/.cargo/git/checkouts/amethyst-fedb0a1032a075ce/6d0e7aa/src/app.rs:820:20
  10: gem_pong::main
             at ./src/main.rs:54:9
  11: core::ops::function::FnOnce::call_once
             at ~/snap/rustup/common/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Your Environment

Operating System: Ubuntu
Operating System Version: 20.04.2 LTS
Version of Amethyst: 0.16.0

## Additional Context

I encountered this bug while working through the Amethyst Book, modified for the differences between 0.15 and 0.16.

**Comment by dragonrider7225** [comment]
I have discovered the `amethyst::assets::LoaderBundle` struct, which provides the missing resources. Since `RenderingBundle` or `RenderToWindow` depends on resources added by `LoaderBundle`, there should be some indication that of that dependency in the docs.
