### ISSUE TITLE
Pass crash

### ISSUE THREAD

**Issue by jojolepro** [amethyst/amethyst#597]
I'm not too sure of what I did, but I crashed a pass.
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::panicking::panic
             at /checkout/src/libcore/panicking.rs:51
  10: <core::option::Option<T>>::unwrap
             at /checkout/src/libcore/macros.rs:20
  11: amethyst_renderer::pass::util::add_textures
             at /home/jojolepro/.cargo/git/checkouts/amethyst-5187f320c494f15f/bb15fa6/amethyst_renderer/src/pass/util.rs:102
  12: amethyst_renderer::pass::util::draw_mesh
             at /home/jojolepro/.cargo/git/checkouts/amethyst-5187f320c494f15f/bb15fa6/amethyst_renderer/src/pass/util.rs:168
  13: <amethyst_renderer::pass::shaded::interleaved::DrawShaded<V> as amethyst_renderer::pipe::pass::Pass>::apply
             at /home/jojolepro/.cargo/git/checkouts/amethyst-5187f320c494f15f/bb15fa6/amethyst_renderer/src/pass/shaded/interleaved.rs:119
  14: <amethyst_renderer::pipe::pass::CompiledPass<P>>::apply
             at /home/jojolepro/.cargo/git/checkouts/amethyst-5187f320c494f15f/bb15fa6/amethyst_renderer/src/pipe/pass.rs:67
  15: <hetseq::list::List<(amethyst_renderer::pipe::pass::CompiledPass<HP>, TP)> as amethyst_renderer::pipe::stage::Passes>::apply
             at /home/jojolepro/.cargo/git/checkouts/amethyst-5187f320c494f15f/bb15fa6/amethyst_renderer/src/pipe/stage.rs:116
  16: <amethyst_renderer::pipe::stage::Stage<L> as amethyst_renderer::pipe::stage::PolyStage>::apply
             at /home/jojolepro/.cargo/git/checkouts/amethyst-5187f320c494f15f/bb15fa6/amethyst_renderer/src/pipe/stage.rs:168
  17: <hetseq::list::List<(HS, hetseq::list::List<()>)> as amethyst_renderer::pipe::pipe::PolyStages>::apply
             at /home/jojolepro/.cargo/git/checkouts/amethyst-5187f320c494f15f/bb15fa6/amethyst_renderer/src/pipe/pipe.rs:71
  18: <amethyst_renderer::pipe::pipe::Pipeline<L> as amethyst_renderer::pipe::pipe::PolyPipeline>::apply
             at /home/jojolepro/.cargo/git/checkouts/amethyst-5187f320c494f15f/bb15fa6/amethyst_renderer/src/pipe/pipe.rs:151
  19: amethyst_renderer::renderer::Renderer::draw
             at /home/jojolepro/.cargo/git/checkouts/amethyst-5187f320c494f15f/bb15fa6/amethyst_renderer/src/renderer.rs:84
  20: <amethyst_renderer::system::RenderSystem<P>>::render
             at /home/jojolepro/.cargo/git/checkouts/amethyst-5187f320c494f15f/bb15fa6/amethyst_renderer/src/system.rs:133
  21: <amethyst_renderer::system::RenderSystem<P> as shred::system::RunNow<'a>>::run_now
             at /home/jojolepro/.cargo/git/checkouts/amethyst-5187f320c494f15f/bb15fa6/amethyst_renderer/src/system.rs:168
  22: shred::dispatch::dispatcher::Dispatcher::dispatch_thread_local
             at /home/jojolepro/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.5.2/src/dispatch/dispatcher.rs:80
  23: shred::dispatch::dispatcher::Dispatcher::dispatch
             at /home/jojolepro/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.5.2/src/dispatch/dispatcher.rs:38
  24: amethyst::app::Application::advance_frame
             at /home/jojolepro/.cargo/git/checkouts/amethyst-5187f320c494f15f/bb15fa6/src/app.rs:201
  25: amethyst::app::Application::run
             at /home/jojolepro/.cargo/git/checkouts/amethyst-5187f320c494f15f/bb15fa6/src/app.rs:129
```

I think it was due to me loading the same Font two times.

**Comment by Rhuagh** [comment]
Looks like one of the textures referenced from `MaterialDefaults` is missing in asset storage

**Comment by torkleyy** [comment]
How?

**Comment by Rhuagh** [comment]
No idea

**Comment by torkleyy** [comment]
@jojolepro Please provide instructions for reproduction.

**Comment by jojolepro** [comment]
I think it was because I had this piece of code repeated two times.
```
let (font,red,blue,green) = {
        let loader = world.read_resource::<Loader>();
        let font = loader.load(
            "fonts/Nunito-Black.ttf",
            TtfFormat,
            Default::default(),
            (),
            &world.read_resource::<AssetStorage<FontAsset>>(),
        );
        let tex_storage = world.read_resource();
        let red = loader.load_from_data([1.0, 0.0, 0.0, 1.0].into(), (), &tex_storage);
        let blue = loader.load_from_data([0.0, 0.0, 1.0, 1.0].into(), (), &tex_storage);
        let green = loader.load_from_data([0.0, 1.0, 0.0, 1.0].into(), (), &tex_storage);
        (font,red,blue,green)
    };
```

**Comment by jojolepro** [comment]
Yes, that's exactly this.

**Comment by torkleyy** [comment]
@jojolepro I cannot reproduce the crash. Could you please provide a more complete example?

**Comment by jojolepro** [comment]
I had an issue with my git which prevents me from commiting to the new branch I made. To replicate the error, do the following:
git clone https://github.com/jojolepro/world-digger
replace src/ui.rs by https://gist.github.com/jojolepro/609327ce5f5c0915ca1bcf1cf84c283e
cargo build && cargo run

The game will load the first ui. When you press the "X" keyboard button, the game will load the second ui, accidentally loading a second time the Font and materials I'm using.

**Comment by torkleyy** [comment]
This bug should be fixed now, I think it was an unsoundness in the asset loading.

**Comment by jojolepro** [comment]
Yeah should be fixed
