### ISSUE TITLE
Strange issue with repaints after deleting entities

### ISSUE THREAD

**Issue by illis** [amethyst/amethyst#625]
Hi all, got a strange issue trying to delete entities after a delay. I've modified the pong demo, to add a comet style tail to it, that is slowly supposed to dissipate over time.

Problem is that it instead of slowly deleting sections in order, it deletes a whole segment, then redraws some backwards, then proceeds to work as its expected.

Kinda hard to explain so I've put the demo here: 
https://github.com/illis/amethyst/tree/bug/tracer 
You can run it with:
cargo run --example pong

Strange thing is that if you lower the frame limit in main.rs from 144 to 30 it seems to work fine.

Not 100% sure if this is a bug, or just something silly that I have done. If any one has any hints, it would be much appreciated.

**Comment by jojolepro** [comment]
Paddles become replaced by dots too. Since we get an unwrap in engine code, this will be considered a bug on our side.
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::panicking::panic
             at libcore/panicking.rs:51
  10: <core::option::Option<T>>::unwrap
             at /checkout/src/libcore/macros.rs:20
  11: amethyst_renderer::pass::util::add_textures
             at amethyst_renderer/src/pass/util.rs:102
  12: amethyst_renderer::pass::util::draw_mesh
             at amethyst_renderer/src/pass/util.rs:168
  13: <amethyst_renderer::pass::flat::interleaved::DrawFlat<V> as amethyst_renderer::pipe::pass::Pass>::apply
             at ./amethyst_renderer/src/pass/flat/interleaved.rs:111
  14: <amethyst_renderer::pipe::pass::CompiledPass<P>>::apply
             at ./amethyst_renderer/src/pipe/pass.rs:67
  15: <hetseq::list::List<(amethyst_renderer::pipe::pass::CompiledPass<HP>, TP)> as amethyst_renderer::pipe::stage::Passes>::apply
             at ./amethyst_renderer/src/pipe/stage.rs:116
  16: <amethyst_renderer::pipe::stage::Stage<L> as amethyst_renderer::pipe::stage::PolyStage>::apply
             at ./amethyst_renderer/src/pipe/stage.rs:168
  17: <hetseq::list::List<(HS, hetseq::list::List<()>)> as amethyst_renderer::pipe::pipe::PolyStages>::apply
             at ./amethyst_renderer/src/pipe/pipe.rs:71
  18: <amethyst_renderer::pipe::pipe::Pipeline<L> as amethyst_renderer::pipe::pipe::PolyPipeline>::apply
             at ./amethyst_renderer/src/pipe/pipe.rs:151
  19: amethyst_renderer::renderer::Renderer::draw
             at ./amethyst_renderer/src/renderer.rs:84
  20: <amethyst_renderer::system::RenderSystem<P>>::render
             at ./amethyst_renderer/src/system.rs:133
  21: <amethyst_renderer::system::RenderSystem<P> as shred::system::RunNow<'a>>::run_now
             at ./amethyst_renderer/src/system.rs:168
```

**Comment by jojolepro** [comment]
ArchLinux 64bit
rustc 1.25

**Comment by Hittherhod** [comment]
Mac OS X High Sierra
rustc 1.25.0

I don't see the panic on my system. I do see the behavior @jojolepro mentioned though.

**Comment by illis** [comment]
Update: managed to get it to panic, after leaving it run for about 20-30s (initally I kept quiting the app, after the first few seconds).

**Comment by torkleyy** [comment]
Maybe this is related to #618, at least the panic is (the default texture is getting freed, which is assumed to be available unconditionally).

**Comment by illis** [comment]
@torkleyy Just tried patching in #627 manually - seems to have fixed the issue :) Thanks heaps!!  I'll wait till its merged in and give it another test, before closing the issue.

**Comment by illis** [comment]
Closing issue: Tested with the latest master; with #627 patched in - all is working well :)
